<div class="introTxt">
    <h1>Über uns</h1>
    <h2>HORISEN – Marketingtechnologie für Marketingprofis</h2>
</div>
<p>
    Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
    when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries,
    but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing 
    Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
</p>

<span class="qoutes">
    <p>„Wer immer das tut, was er kann, bleibt immer das, was er ist.”</p>
    <p>Henry Ford</p>
</span>
<p>Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
<h3>Mehr über HORISEN:</h3>

<h2>Unsere Vision</h2>
<p>Wir möchten eine einzige Plattform bieten, die alle Kommunikationskanäle von Audio-, Web- Mobil- und sozialen Medien in
Kombination mit den klassischen Offline-Medien miteinander verbindet. Damit soll ein einzelner cross-medialen Kanal 
geschaffen, sowie nahtlos integrierte digitale Kundenerfahrungen ermöglicht werden können. Wir verwenden dafür gerne das 
Bild eines Menschen, der von vielen „kleinen Helfern“ umgeben ist. Diese kleinen Helfer sind unsichtbare elektronische 
Taschenmesser, die jeden Tag im Einsatz stehen und dir ohne Einschränkung helfen können, unabhängig vom Standort, der 
Technologie oder der Vereinbarkeit von Quellen.</p>

<h2>Unsere Aufgabe</h2>
<p>Ne ubique honestatis mea, ea nobis indoctum dissentias sed. Utamur expetenda ocurreret vel at. Dicant regione invidunt sit ei, mei graeci ceteros democritum ex. Per ei tale volumus. Sed at euismod argumentum definitionem, brute volumus usu ne, officiis convenire rationibus per te.</p>

<h2>Wir treffen unsere Partner an ihren Meilensteinen</h2>
<p>Ne ubique honestatis mea, ea nobis indoctum dissentias sed. Utamur expetenda ocurreret vel at. Dicant regione invidunt sit ei, mei graeci ceteros democritum ex. Per ei tale volumus. Sed at euismod argumentum definitionem, brute volumus usu ne, officiis convenire rationibus per te.</p>

<h2>Philosophie</h2>
<p>Ne ubique honestatis mea, ea nobis indoctum dissentias sed. Utamur expetenda ocurreret vel at. Dicant regione invidunt sit ei, mei graeci ceteros democritum ex. Per ei tale volumus. Sed at euismod argumentum definitionem, brute volumus usu ne, officiis convenire rationibus per te.</p>