<?php
//we don't need layout - the page will contain all needed
$this->layout()->setLayout('intro');
?>


<div style="text-align:center; padding-top:200px;">

<h2>Dies ist ein Intro-Seite</h2>

<p>Fünf Jahrhunderte, sondern auch den Sprung in die elektronische Schrift, nahezu unverändert. <br /> Es wurde in den 1960er Jahren mit der Veröffentlichung von Letraset Blätter Lorem Ipsum Passagen populär, und in jüngerer Zeit mit dem Desktop zu veröffentlichen.</p>
</div>