<div class="introTxt">
    <h1>Landing Pages</h1>
    <h2>Schnelle Umwandlung in effektiven Inhalt</h2>
</div>
<p>Tools zum Handlungsaufruf, die Kunden schnell fesseln!</p>
<div class="row innerRow">
    <div class="col-md-9 listWrapper">
        <div class="row listGroup">
            <div class="collapseContent col-md-6">
                <h3>Du willst</h3>
                <ul class="collapseContentBox">
                    <li>Effektive neue Promotion-Webseite</li>
                    <li>Zeitlich begrenzte Promotion-Kampagnen</li>
                    <li>Besseres Produkt-„Schaufenster“</li>
                    <li>Attraktives Design deiner Verkaufsseite</li>
                    <li>Kurze Time-to-Market deiner Promotion-Seite</li>
                </ul>
            </div>
            <div class="collapseContent col-md-6">
                <h3>Wir bieten</h3>
                <ul class="collapseContentBox">
                    <li>Individuell gestaltbare Webseiten-Elemente</li>
                    <li>Entwicklung von flexiblen und schnellen Promotion-Seiten</li>
                    <li>Automatisierungsprozess zum Aufbau von Kommunikation mit den Kunden</li>
                    <li>Viele Optionen des Kundendesigns vorhanden</li>
                    <li>Schnelle Umsetzung deiner Landing Page</li>
                </ul>
            </div>
        </div>
        <div class="row listGroup">
            <div class="collapseContent col-md-6">
                <h3>Eigenschaften</h3>
                <ul class="collapseContentBox">
                    <li>Freie Textfelder</li>
                    <li>Frei bewegliche Elemente</li>
                    <li>Automatische E-Mail-Nachrichten</li>
                    <li>Kunde zum Handeln auffordern</li>
                    <li>A/B-Tests inklusive oder auf Anfrage</li>
                    <li>Bericht zur Konversionsanalyse</li>
                    <li>Kontakt-Datenbank und hochwertiger Datenexport</li>
                    <li>Kundenspezifische Designs und CSS-Anpassungen</li>
                </ul>
            </div>
            <div class="collapseContent col-md-6">
                <h3>Zweck</h3>
                <ul class="collapseContentBox">
                    <li>Schnelle Konversionen</li>
                    <li>Festhalten von Qualitätskontakten</li>
                    <li>Sofortverkauf</li>
                    <li>Frühe Produkt-Promotion</li>
                    <li>Bewertung der Servicequalität</li>
                    <li>Separates Produktschaufenster</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="row">
            <div class="col-md-12 col-xs-6 innerPageImage">
                <?php echo $this->renderPicture('landing-page-1', 'inner/landing-page/landing-page-1', 'Landing pages are product shopping windows', '.jpg');?>
            </div>
            <div class="col-md-12 col-xs-6 innerPageImage">
                <?php echo $this->renderPicture('landing-page-2', 'inner/landing-page/landing-page-2', 'New promo pages made thanks to landing pages', '.jpg');?>
            </div>
        </div>
    </div>
</div>
<section class="collapsibleSection">
    <h2>Beschreibung</h2>
    <div class="row description">
        <div class="col-md-9">
            <p>Der Zweck effektiver Landing Pages besteht in der Konversion von Besuchern in Registrierte. Aber wie? Eine attraktive Landing 
                Page mit tollem Design und einem Kundenkontaktformular reicht nicht. Landing Pages müssen mit den Besuchern sprechen und 
                deren Bedürfnisse und Erwartungen verstehen. Deshalb kann eine einzigartige Seite innert weniger Sekunden Wunder für dein 
                Geschäft vollbringen.</p> 

            <p>Landing Pages sind sehr flexibel in Bezug auf Seitenanpassungen und Formkreationen. Durch smarte Inhaltsverteilung kannst du
                eine Menge Verkehr generieren und konvertieren, der nur hier ankommt.  Egal ob du eine spezielle Promotion oder eine zeitlich 
                begrenzte Kampagne für dein neues Produkt/Service organisierst - diese Art von Webpräsentation wird den Konversionsprozess 
                beschleunigen. Landing Pages sollen die Aufmerksamkeit des Nutzers wecken, was ein attraktives Design der Landing-Page 
                voraussetzt.</p>

            <p>Ausserdem solltest du vor der Freigabe der Landing Page einen A/B-Test machen. So kannst du sicher sein, welche Art von
                Inhalt, Seitenkomposition und Design am besten wirkt! Mit individuellen Aufrufen zum Handeln kannst du leicht die richtigen 
                Besucher anziehen, damit sie dein Angebot oder dein Verkaufsargument sehen. Du hast die Möglichkeit alle Elemente zu testen 
                – inklusive Überschriften, Handlungsaufrufe und Bilder. Du kannst auch andere Landing Pages ansehen und herausfinden, 
                welche Version die meisten Konversionen bringt.</p>

            <p>Mit deiner spezifischen URL oder Sub-Domäne kann eine Landing Page leicht analysiert werden. Jede Promotion kann
                permanent gemessen werden, um für zukünftige Promotionen falls nötig Optimierungen oder Anpassungen vorzunehmen.</p> 

            <p>Die automatisierten Email-Mitteilungen sind ein wichtiger Punkt für erfolgreiches Email-Marketing und für regelmässige 
                Newsletter-Aktualisierungen. So baust du nicht nur Kommunikation zu deinen Kunden auf, du erinnerst sie auch an andere 
                Angebote deiner Marke oder Marktnische.</p>

        </div>
        <div class="col-md-3">
            <div class="row">
                <div class="col-md-12 col-xs-6 innerPageImage">
                    <?php echo $this->renderPicture('landing-page-3', 'inner/landing-page/landing-page-3', 'Landing pages allow fully custom design', '.jpg');?>
                </div>
                <div class="col-md-12 col-xs-6 innerPageImage">
                    <?php echo $this->renderPicture('landing-page-4', 'inner/landing-page/landing-page-4', 'Instant selling happens with landing pages', '.jpg');?>
                </div>
            </div>
        </div>  
    </div>
</section>
<section class="collapsibleSection">
    <h2>Vorbereitungen</h2>
    <div class="row">
        <div class="col-md-12">  
            <h3>Vorbereitungen</h3>
            <ol>
                <li>Idee für eine Promotion (z. B. saisonale Promotion, Verkäufe, Handlungsaufruf zum Mitmachen usw.)</li>
                <li>Textelemente schreiben, inklusive Handlungsaufruf</li>
                <li>Felder für Kontaktformular wählen oder Email-Abo</li>
                <li>Design-Elemente und visuelle Darstellung festlegen</li>
                <li>Test durchführen und die beste Version für dich finden</li>
                <li>Gib deine Landing Page frei und promote sie durch verschiedene Offline-Online-Medien, inkl. Social Media-Kanäle</li>
            </ol>
            <h3>Wie deine Kunden auf deiner Landing Page ankommen</h3>
            <ol>
                <li>Du hast ein Inserat kreiert</li>
                <li>Das Inserat erscheint auf: deinen Promotion-Flyers, dem Werbebanner, einer TV-Werbung, der Produktverpackung oder Social Media-Seiten wie Facebook oder Google Ads</li>
                <li>Wenn sie auf deine Webseiten-URL gehen oder den Promo-Link anklicken (Online-Ad) kommen die Besucher zuerst wieder auf die Landing Page</li>
                <li>Sie sehen den attraktiven Inhalt und geben ihre Daten an/beantworten die Frage oder was du sonst als Promotion vorgesehen hast</li>
                <li>Nachdem sie eine Email-Nachricht erhalten haben, können sie zu einer anderen Aktivität wechseln; andernfalls ist das
                    der letzte Schritt – falls Preise oder Rabatte. für später angekündigt sind</li>
            </ol>
        </div>
    </div>
</section>