<div class="introTxt">
    <h1>Angebote</h1>
    <h2>Wir setzen ohne Grenzen um</h2>
</div>
<p>Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions more recently with desktop publishing software.</p>
<p>Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions more recently with desktop publishing software.</p>
<h2>Leistungen</h2>
<section class="collapsibleSection designSection">
    <h3>Beratung, Analyse und Optimierung</h3>
    <div class="row description">
        <div class="col-md-12 listWrapper">
            <div class="row listGroup">
                <div class="collapseContent col-md-7">
                    <?php echo $this->renderPicture('consultation', 'inner/designs/designs1', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
                <div class="collapseContent col-md-5">
                    <p>Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions more recently with desktop publishing software.</p>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="collapsibleSection designSection">
    <h3>Logodesign</h3>
    <div class="row description">
        <div class="col-md-12 listWrapper">
            <div class="row listGroup">
                <div class="collapseContent col-md-7">
                    <?php echo $this->renderPicture('logo-design', 'inner/designs/designs2', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
                <div class="collapseContent col-md-5">
                    <p>Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions more recently with desktop publishing software.</p>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="collapsibleSection designSection">
    <h3>Corporate Design</h3>
    <div class="row description">
        <div class="col-md-12 listWrapper">
            <div class="row listGroup">
                <div class="collapseContent col-md-7">
                    <?php echo $this->renderPicture('corporate-design', 'inner/designs/designs3', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
                <div class="collapseContent col-md-5">
<p>Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions more recently with desktop publishing software.</p>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="collapsibleSection designSection">
    <h3>Bildbearbeitung und Illustrationen</h3>
    <div class="row description">
        <div class="col-md-12 listWrapper">
            <div class="row listGroup">
                <div class="collapseContent col-md-7">
                    <?php echo $this->renderPicture('image-editing', 'inner/designs/designs4', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
                <div class="collapseContent col-md-5">
                    <p>Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions more recently with desktop publishing software.</p>
		    <p>Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like including versions more recently with desktop publishing software.</p>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="collapsibleSection designSection">
    <h3>Flyer- und Inseratengestaltung</h3>
    <div class="row description">
        <div class="col-md-12 listWrapper">
            <div class="row listGroup">
                <div class="collapseContent col-md-7">
                    <?php echo $this->renderPicture('flyer', 'inner/designs/designs5', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
                <div class="collapseContent col-md-5">
		    <p>Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like including versions more recently with desktop publishing software.</p>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="collapsibleSection designSection">
    <h3>Editorial Design – Broschüren, Magazine, Bücher etc.</h3>
    <div class="row description">
        <div class="col-md-12 listWrapper">
            <div class="row listGroup">
                <div class="collapseContent col-md-7">
                    <?php echo $this->renderPicture('editorial-design', 'inner/designs/designs6', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
                <div class="collapseContent col-md-5">
		    <p>Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like including versions more recently with desktop publishing software.</p>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="collapsibleSection designSection">
    <h3>Verkaufsförderung</h3>
    <div class="row description">
        <div class="col-md-12 listWrapper">
            <div class="row listGroup">
                <div class="collapseContent col-md-7">
                    <?php echo $this->renderPicture('sales-collateral', 'inner/designs/designs7', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
                <div class="collapseContent col-md-5">
		    <p>Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like including versions more recently with desktop publishing software.</p>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="collapsibleSection designSection">
    <h3>Verpackungsdesign</h3>
    <div class="row description">
        <div class="col-md-12 listWrapper">
            <div class="row listGroup">
                <div class="collapseContent col-md-7">
                    <?php echo $this->renderPicture('packaging', 'inner/designs/designs8', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
                <div class="collapseContent col-md-5">
		    <p>Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like including versions more recently with desktop publishing software.</p>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="collapsibleSection designSection">
    <h3>(Responsive) Webdesign</h3>
    <div class="row description">
        <div class="col-md-12 listWrapper">
            <div class="row listGroup">
                <div class="collapseContent col-md-7">
                    <?php echo $this->renderPicture('web-design', 'inner/designs/designs9', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
                <div class="collapseContent col-md-5">
		    <p>Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like including versions more recently with desktop publishing software.</p>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="collapsibleSection designSection">
    <h3>Social Media Kampagnen</h3>
    <div class="row description">
        <div class="col-md-12 listWrapper">
            <div class="row listGroup">
                <div class="collapseContent col-md-7">
                    <?php echo $this->renderPicture('social-media', 'inner/designs/designs10', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
                <div class="collapseContent col-md-5">
		    <p>Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like including versions more recently with desktop publishing software.</p>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="collapsibleSection designSection">
    <h3>Video Tutorials, Firmenvorstellungen</h3>
    <div class="row description">
        <div class="col-md-12 listWrapper">
            <div class="row listGroup">
                <div class="collapseContent col-md-7">
                    <?php echo $this->renderPicture('video-tutorial', 'inner/designs/designs11', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
                <div class="collapseContent col-md-5">
<p>Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions more recently with desktop publishing software.</p>
		    <p>Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like including versions more recently with desktop publishing software.</p>
                </div>
            </div>
        </div>
    </div>
</section>