<div class="introTxt">
    <h1>Fliesenkonzept</h1>
    <h2>Display- Inhalte über Fliesen Konzept</h2>
</div>
<p>Lorem ipsum dolor sit amet, movet putant usu in, eam iriure maiestatis ex!Lorem ipsum dolor sit amet, movet putant usu in, eam iriure maiestatis ex. Vet putant usu in, eam iriure maiestatis</p>
<p>Lorem ipsum dolor sit amet, movet putant usu in, eam iriure maiestatis ex!</p>
<div class="row servicesRow">
    <h3>Unsere Bereiche</h3>
    <div class="col-md-6">
        <ul>
            <li>Beratung, Analyse und Optimierung</li>
            <li>Logodesign</li>
            <li>Corporate Design</li>
            <li>Bildbearbeitung und Illustrationen</li>
            <li>Flyer- und Inseratengestaltung</li>
            <li>Broschüren-Gestaltung</li>
        </ul>
    </div>
    <div class="col-md-6">
        <ul>
            <li>Magazindesign</li>
            <li>Verkaufsförderung</li>
            <li>Verpackungsdesign</li>
            <li>Webdesign (Responsive)</li>
            <li>Social Media Kampagnen</li>
            <li>Videotutorials, Firmenvorstellungen</li>
        </ul>
    </div>
</div>
<div class="graphicOverview">
    <div class="row">
        <div class="col-md-4 designInnerPageImage">
            <?php echo $this->renderPicture('logo-design', 'inner/services/logo-design', 'Placeholder image for our services', '.jpg');?>
            <p>Logodesign</p>
        </div>
        <div class="col-md-4 designInnerPageImage">
            <?php echo $this->renderPicture('corporate-design', 'inner/services/corporate-design', 'Placeholder image for our services', '.jpg');?>
            <p>Corporate Design</p>
        </div>
        <div class="col-md-4 designInnerPageImage">
            <?php echo $this->renderPicture('illustration', 'inner/services/illustration', 'Placeholder image for our services', '.jpg');?>
            <p>Bildbearbeitung und Illustrationen</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4 designInnerPageImage">
            <?php echo $this->renderPicture('flyer', 'inner/services/flyer', 'Placeholder image for our services', '.jpg');?>
            <p>Flyer- und Inseratengestaltung</p>
        </div>
        <div class="col-md-4 designInnerPageImage">
            <?php echo $this->renderPicture('magazin-design', 'inner/services/magazin-design', 'Placeholder image for our services', '.jpg');?>
            <p>Magazindesign</p>
        </div>
        <div class="col-md-4 designInnerPageImage">
            <?php echo $this->renderPicture('sales-promotion', 'inner/services/sales-promotion', 'Placeholder image for our services', '.jpg');?>
            <p>Verkaufsförderung</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4 designInnerPageImage">
            <?php echo $this->renderPicture('package-design', 'inner/services/package-design', 'Placeholder image for our services', '.jpg');?>
            <p>Verpackungsdesign</p>
        </div>
        <div class="col-md-4 designInnerPageImage">
            <?php echo $this->renderPicture('multimedia-campaigns', 'inner/services/multimedia-campaigns', 'Placeholder image for our services', '.jpg');?>
            <p>Multimedia-Kampagnen</p>
        </div>
        <div class="col-md-4 designInnerPageImage">
            <?php echo $this->renderPicture('video-tutorials', 'inner/services/video-tutorials', 'Placeholder image for our services', '.jpg');?>
            <p>Videotutorials, Firmenvorstellungen</p>
        </div>
    </div>
</div>
