<div class="introTxt">
    <h1>Videos</h1>
    <h2>Forme dein Unternehmen mit emotionalem Storytelling</h2>
</div>
<p>Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions more recently with desktop publishing software.</p>
		    <p>Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like including versions more recently with desktop publishing software.</p>
<div class="row servicesRow">
    <h3>Video Design</h3>
    <div class="col-md-6">
        <ul>
            <li>Produkt / Service Videos</li>
            <li>Animationen</li>
            <li>Firmenvideos</li>
            <li>Showcase / Testimonial Videos</li>
        </ul>
    </div>
    <div class="col-md-6">
        <ul>
            <li>Verkaufsvideos</li>
            <li>Tutorial Videos</li>
            <li>Eventvideos</li>
            <li>Präsentationsvideos</li>
        </ul>
    </div>
</div>
<div class="graphicOverview">
    <div class="row">
        <div class="col-md-4 videoInnerPageImage">
            <?php echo $this->renderPicture('product', 'inner/videos/product', 'Placeholder image for videos', '.jpg');?>
            <p>Produkt / Service Videos</p>
        </div>
        <div class="col-md-4 videoInnerPageImage">
            <?php echo $this->renderPicture('animations', 'inner/videos/animations', 'Placeholder image for videos', '.jpg');?>
            <p>Animationen</p>
        </div>
        <div class="col-md-4 videoInnerPageImage">
            <?php echo $this->renderPicture('corporate-videos', 'inner/videos/corporate-videos', 'Placeholder image for videos', '.jpg');?>
            <p>Firmenvideos</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4 videoInnerPageImage">
            <?php echo $this->renderPicture('showcase', 'inner/videos/showcase', 'Placeholder image for videos', '.jpg');?>
            <p>Showcase / Testimonial Videos</p>
        </div>
        <div class="col-md-4 videoInnerPageImage">
            <?php echo $this->renderPicture('sales-videos', 'inner/videos/sales-videos', 'Placeholder image for videos', '.jpg');?>
            <p>Verkaufsvideos</p>
        </div>
        <div class="col-md-4 videoInnerPageImage">
            <?php echo $this->renderPicture('tutorial-videos', 'inner/videos/tutorial-videos', 'Placeholder image for videos', '.jpg');?>
            <p>Tutorial Videos</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4 videoInnerPageImage">
            <?php echo $this->renderPicture('event-videos', 'inner/videos/event-videos', 'Placeholder image for videos', '.jpg');?>
            <p>Eventvideos</p>
        </div>
        <div class="col-md-4 videoInnerPageImage">
            <?php echo $this->renderPicture('presentation-videos', 'inner/videos/presentation-videos', 'Placeholder image for videos', '.jpg');?>
            <p>Präsentationsvideos</p>
        </div>
    </div>
</div>
