<?php
    $this->headScript()->appendFile('/plugins/hfb/js/jquery.hfbSelect.js');
    $this->headScript()->appendFile('/plugins/hfb/js/jquery.hfbSearch.js');
    $this->headScript()->appendFile('/plugins/hfb/js/jquery.hfbList.js');
    $this->headScript()->appendFile('/modules/auth/js/list.js');
?>
<script type="text/javascript">
    function getEditUrl(id){
        return sprintf('/%s/auth/admin-role/role-edit/id/%d',CURR_LANG,id);
    }

    function editDialog(id){
        ajaxForm.newTab(getEditUrl(id),{
            onContent: function(newTabId){
                //console.log(newTabId);
            },
            onClose: function(success){
                if(success){
                    updateList();
                }
            },
            width: 'auto',
            height: 'auto'
        });
    }
    
   
    initList('/' + CURR_LANG + '/auth/admin-role/role-list/',{},function(me,data){
       /* $("#listContainer").find("a.edit").click(function(){
            editDialog($(this).data('id'));
            return false;
        });*/
        $("#listContainer").find("a.delete").click(function(){
            alert('delete'+$(this).data('id'));
            return false;
        });
    });
    //init select filter
    $(document).ready(function(){
        $("#langFilter").change(function(){
            updateList('langFilter',$(this).val());
        });
        $("body").on("updateList", function(){
            updateList();
        });
         $("#filter").click(function(){
            var params = $("#listContainer").data('params');
            params['name'] = $('#name').val();
            $("#listContainer").hfbList({
                'params': params
            });
            return false;
        })
        /*$(".add").click(function(){
            editDialog(null);
            return false;
        });*/
    });
</script>
<div class="hcms_content_top">
    <h1><?php echo $this->translate('Roles'); ?></h1>
</div>
<div class="hcms_content">
    <div class="res-tabs">
        <ul class="tab-list">
            <li class="styled-apps"><?php echo $this->translate('List ');?></li>
        </ul>
        <div class="articles"> 
            <div>
                <div class="hcms_btn_actions roles">
                    <div class="btn-block">
                        <a href="#" class="add btn btn-small btn-primary"><i class="icon-plus-med"></i><?php echo $this->translate('Add new'); ?></a>
                        <div class="hcms_search">
			    <div class="input-group">
				<input name="searchFilter" id="searchFilter" type="text" value="" />
				<div class="input-group-btn">
				    <a href="#" class="btn btn-small btn-primary" id="searchExecute"><?php echo $this->translate("Search"); ?></a>
				</div>
			    </div>
			</div>
                    </div>
                    <div class="btn-block">
			<div class="hcms_block">
			    <div class="input-group">
				<input type="text" class="role-input" name="name" id="name" value="" maxlength="100" placeholder="Name"/>
				<div class="input-group-btn">
				    <a href="#" class="btn btn-small btn-primary" id="filter">Filter</a>
				</div>
			    </div>
			</div>
                    </div>
                </div>
                <table class="hcms_table adminList" width="100%">
                    <thead>
                        <tr>
                            <th><a href="#" class="sort" data-column="name"><?php echo $this->translate('Name');?><b></b></a></th>
                        </tr>
                    </thead>
                    <tbody id="listContainer">

                    </tbody>
                </table>
                <div id="pager" class="pager"></div>
            </div>
        </div>
    </div>
    
</div>
<script type="text/html" id="records_tpl">
<% if (rows.length > 0){
    var rowClass = 'odd';
    %>
    <% for ( var i = 0; i < rows.length; i++ ){
        rowClass = (i % 2 == 0)? 'even':'odd';
    %>
        <tr class="<%=rowClass%>">
            <td class="fixed-width">
               <span><%=rows[i].name%></span>
                <ul class="hcms_menu_actions">
                    <li><a href="#" class="edit" data-id="<%=rows[i].id%>"><span><?php echo $this->translate('Edit');?></span></a></li>
                    <li><a href="#" class="delete" data-id="<%=rows[i].id%>"><span><?php echo $this->translate('Delete');?></span></a></li>
                </ul>
            </td>
        </tr>
    <% } %>
<% } %>
</script>
<script type="text/javascript">
/*res-tables*/
    $(function() {
        var rt = ".res-tabs";
        // initialize NaviBar (test version)
        $(rt).restabs({
            context_obj: this,
            responsiveMode: true,
            tabPlus: true,
            resizeTimeOut: 600,
            showRemove: true
        });
        // add end tab    
        $("#listContainer").on("click", "a.edit", function(e) {
            e.preventDefault();
            var that = $(this);
            var title =  $(this).parent("li").parent("ul").parent("td").children("span").text();
            function addNewTab(){
                var ids = $(rt).restabs("addEndTab");
                setTab(ids, title);
                $(rt).restabs("activateTab", {tabId: ids.tabId});
                editDialog(that.data('id'),that.data('type_id'));  
                var tabOpenedId = "#" + ids.tabId;
                $(tabOpenedId).attr("data-pageId", that.attr("data-id"));
            }
            
            
            var numOfTabs = $(".res-tabs .tab-list li").length;
            var itIsOpen = 0;
            if (numOfTabs == 1){
                addNewTab();
            } else {
                $(".res-tabs .tab-list li").each(function(){
                    if ($(this).text() == title) {
                        itIsOpen = itIsOpen + 1;
                    }  
                });
                if (itIsOpen == 0) {
                    addNewTab();
                }
            } 
        });

        var setTab = function(ids, editTitle) {
            $(rt).restabs("setTab", ids, {
                title: editTitle,
                content: " ",
                removable: false
            });
        };
        // add new page tab
       $(".add").click(function(e){
            e.preventDefault();
            var ids = $(rt).restabs("addEndTab");
            setTab(ids, "Add new");
            $(rt).restabs("activateTab", {tabId: ids.tabId});
            editDialog(null);
           
            return false;
        });
    });
</script>