<?php
    $this->headScript()->appendFile('/plugins/imagebrowser/bs/jquery.imagebrowserdialog.js');
    $this->headScript()->appendFile('/plugins/jscolor/jscolor.js');
    $this->headScript()->appendFile('/modules/admin/js/config.js');
    $this->headLink()->appendStylesheet('/plugins/jscolor/jscolor.css');
?>

<script type="text/javascript">
    $(function () {
            $('html').click(function(e) {
                $('.popoverGAconfig').popover('hide');
            });

            $('.popoverGAconfig').popover({
                toggleSideBar: true,
                tranistion: true,
                html: true,
                trigger: 'manual'
            }).click(function(e) {
                $(this).popover('toggle');
                e.stopPropagation();
                return false;
                
            });
        });
</script>
    
<div class="hcms_content_top">
    <h1><?php echo $this->translate('Google Services'); ?> </h1>
</div>
<div class="hcms_content GAContainer" >
    <div class="res-tabs">
	<ul class="tab-list">
            <li class="styled-apps"><?php echo $this->translate('Custom search');?></li>
            <li class="styled-apps"><?php echo $this->translate('Webmaster Tools');?></li>
            <li class="styled-apps"><?php echo $this->translate('Google Tags Manager');?></li>
            <li class="styled-apps"><?php echo $this->translate('Web Robots');?></li>
	</ul>
	<div class="articles">
            <div>
                <div id="Gsc">
                    <div class="infoContainer">
                        <h2><?php echo $this->translate('Google Custom Search ');?></h2>
                        <p><?php echo $this->translate("Google Custom Search lets user to include a search engine on his website to help his visitors find the information they're looking for. ");?></p>
                    </div>
                    
                    <form method="post" class="hcms_form configForm " title="<?php echo $this->translate('Edit GSC Configuration');?>" action="<?php echo $this->url(array('controller' => 'google-service', 'action' => 'edit')) ?>" enctype="application/x-www-form-urlencoded">
                        <input type="hidden" id="data[id]" value="<?php echo $this->escape($this->data['id']);?>" name="data[id]"/>
                        <div class="configFormContainer">
                            <label for="data[active]"><?php echo $this->translate('Status');?>:</label>
                             <select  id="data[active]" name="data[active]">
                                <option <?php if (isset($this->data['settings']['gsc']['active'] ) && $this->data['settings']['gsc']['active'] == true) { ?>selected="selected" <?php } ?> value="true"><?php echo $this->translate('Active');?></option>
                                <option <?php if (isset($this->data['settings']['gsc']['active']) && $this->data['settings']['gsc']['active'] == false) { ?>selected="selected"<?php } ?> value="false"><?php echo $this->translate('Inactive');?> </option>
                            </select> 
                            <a href="#" class="popoverGAconfig" data-toggle="popover" data-placement="bottom" title="" data-content="<?php echo $this->translate("Toggles ON and OFF Google's search engine on front end of users web site."); ?>"><i class="fa fa-info-circle"></i></i></a>
                            <?php echo $this->errorMessages($this->errors['active']);?>
                        </div>
                        <div id="hideSetingsSearch">
                            <div class="configFormContainer">
                                <label for="data[name]"><?php echo $this->translate('Name');?>:</label>
                                <input type="text" name="data[name]" id="data[settings][gsc][name]" value="<?php echo (isset($this->data['settings']['gsc']['name']))? $this->escape($this->data['settings']['gsc']['name']):'';?>" maxlength="100" />
                                <a href="#" class="popoverGAconfig" data-toggle="popover" data-placement="bottom" title="" data-content="<?php echo $this->translate("Here you can name your search engine."); ?>"><i class="fa fa-info-circle"></i></a>
                                <?php echo $this->errorMessages($this->errors['name']);?>
                            </div>

                            <div class="configFormContainer">
                                <label for="data[cx]"><?php echo $this->translate('Cx - Search Engine ID');?>:</label>
                                <input type="text" size="30"  value="<?php echo (isset($this->data['settings']['gsc']['cx']))? $this->escape($this->data['settings']['gsc']['cx']):"";?>" id="data[cx]" name="data[cx]" maxlength="60"/>
                                <a href="#" class="popoverGAconfig" data-toggle="popover" data-placement="bottom" title="" data-content="<?php echo $this->translate("You can find Custom Search Engine ID on the 'Basics' tab, of the Custom Search control panel, of your account. "); ?>"><i class="fa fa-info-circle"></i></a>
                                 <?php echo $this->errorMessages($this->errors['cx']);?>
                            </div>
                            <div class="collapslistHolder gsc-collapslist">
                                <div id="colist-1" class="collapslist ri h-tabs">
                                    <div class="article expanded">
                                        <div class="heading">
                                            <h2 class="title"><i class="icon-minus-small"></i><?php echo $this->translate('Results Custom Styles');?></h2>
                                        </div>
                                        <div class="content-holder">
                                            <div class="content gsc-content">
                                                <table class="hcms_table">
                                                    <thead>
                                                        <tr>
                                                            <th><?php echo $this->translate('Element');?></th>
                                                            <th><?php echo $this->translate('Font color');?></th>
                                                            <th style="text-align:center;"><?php echo $this->translate('Font size');?></th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                        <tr>
                                                            <td contenteditable="true"><?php echo $this->translate('Title');?></td>
                                                            <td>
                                                                <input type="text" class="color gs-title" value="<?php echo (isset($this->data['settings']['gsc']['css']['.gs-title']['color']))? $this->escape($this->data['settings']['gsc']['css']['.gs-title']['color']) : "#609";?>" id="data[title-color]" name="data[title-color]" maxlength="7"/>
                                                                
                                                                <?php echo $this->errorMessages($this->errors['title-color']);?>
                                                            </td>
                                                            <td>
                                                                <select id="data[settings][css][.gs-title][font-size]" class="gs-title" name="data[title-font-size]">
                                                                    <?php for($i=10; $i <= 20; $i++){ ?>
                                                                    <option <?php if (isset($this->data['settings']['gsc']['css']['.gs-title']['font-size']) && $this->data['settings']['gsc']['css']['.gs-title']['font-size'] == $i.'px') { ?>selected="selected" <?php } ?> value="<?php echo $i.'px' ?>"><?php echo $i.'px' ?></option>
                                                                    <?php } ?>
                                                                </select>
                                                                
                                                                <?php echo $this->errorMessages($this->errors['title-font-size']);?>
                                                            </td>
                                                        </tr>
                                                        <tr>
                                                            <td contenteditable="true"><?php echo $this->translate('Snippet');?></td>
                                                            <td>
                                                                <input type="text" class="color gs-snippet"  value="<?php echo (isset($this->data['settings']['gsc']['css']['.gs-bidi-start-align']['color']))? $this->escape($this->data['settings']['gsc']['css']['.gs-bidi-start-align']['color']) : "#545454";?>" id="data[snippet-color]" name="data[snippet-color]" maxlength="7"/>
                                                                
                                                                <?php echo $this->errorMessages($this->errors['snippet-color']);?>
                                                            </td>
                                                            <td>
                                                                 <select id="data[settings][css][.gs-bidi-start-align][font-size]" class="gs-snippet" name="data[snippet-font-size]">
                                                                    <?php for($i=10; $i <= 20; $i++){ ?>
                                                                    <option <?php if (isset($this->data['settings']['gsc']['css']['.gs-bidi-start-align']['font-size']) && $this->data['settings']['gsc']['css']['.gs-bidi-start-align']['font-size'] == $i.'px') { ?>selected="selected" <?php } ?> value="<?php echo $i.'px' ?>"><?php echo $i.'px' ?></option>
                                                                    <?php } ?>
                                                                </select>
                                                                
                                                                <?php echo $this->errorMessages($this->errors['snippet-font-size']);?>
                                                            </td>
                                                        </tr>
                                                        <tr>
                                                            <td contenteditable="true"><?php echo $this->translate('Bottom url');?></td>
                                                            <td>
                                                                <input type="text" class="color gs-visibleUrl" value="<?php echo (isset($this->data['settings']['gsc']['css']['.gs-visibleUrl']['color']))? $this->escape($this->data['settings']['gsc']['css']['.gs-visibleUrl']['color']) : "#006621";?>" id="data[visible-url-color]" name="data[visible-url-color]" maxlength="7"/>
                                                                <?php echo $this->errorMessages($this->errors['snippet-color']);?>
                                                            </td>
                                                            <td>
                                                                <select id="data[settings][css][.gs-bidi-start-align][font-size]" class="gs-visibleUrl" name="data[visible-url-font-size]">
                                                                    <?php for($i=10; $i <= 20; $i++){ ?>
                                                                    <option <?php if (isset($this->data['settings']['gsc']['css']['.gs-visibleUrl']['font-size']) && $this->data['settings']['gsc']['css']['.gs-visibleUrl']['font-size'] == $i.'px') { ?>selected="selected" <?php } ?> value="<?php echo $i.'px' ?>"><?php echo $i.'px' ?></option>
                                                                    <?php } ?>
                                                                </select>
                                                                
                                                                <?php echo $this->errorMessages($this->errors['visible-url-font-size']);?>
                                                            </td>
                                                        </tr>
                                                    </tbody>
                                                </table>
                                                <table class="hcms_table gsc-preview">
                                                    <thead>
                                                        <tr><th style="text-align:center;" class="gpicker-cell"><?php echo $this->translate('Preview');?></th></tr>
                                                    </thead>
                                                    <tbody>
                                                        <tr>
                                                            <td class="gs-snippet-preview gpicker-cell">
                                                                <img src="/modules/admin/images/dummy.jpg" alt="horisen logo" />
                                                                <a class="gs-title" href="javascript:void(0)"> Demo search result title</a><br />
                                                                <div class="gs-snippet demo-result-snippet" id="demo-result-snippet"> Demo search result snippet, which could span several lines ... </div>
                                                                <div class="gs-visibleUrl gs-visibleUrl-long demo-result-url"> www.result.preview/demo </div>
                                                            </td>
                                                        </tr>
                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>  
                        </div>
                    </form>
                </div>
            </div>
            <div>
                <div id="WMT">
                    <div class="infoContainer">
                        <h2><?php echo $this->translate('Webmaster Tools ');?></h2>
                        <p><?php echo $this->translate("Webmaster Tools is a free service offered by Google that helps to monitor and maintain site's presence in Google Search results. It help understand how Google views site and optimize its performance in search results. ");?></p>
                    </div>
                    <form method="post" class="hcms_form configForm " title="<?php echo $this->translate('Edit Configuration');?>" action="<?php echo $this->url(array('controller' => 'google-service', 'action' => 'edit')) ?>" enctype="application/x-www-form-urlencoded">
                            <div id="colist-1" class="collapslist ri h-tabs">
                                    <div class="content-holder">
                                        <div class="content">
                                            <div class="configFormContainer">
                                                <label for="data[wmt_active]"><?php echo $this->translate('Status');?>:</label>
                                                <select  id="data[wmt_active]" name="data[wmt_active]">
                                                   <option <?php if (isset($this->data['settings']['tags']['wmt']['active'] ) && $this->data['settings']['tags']['wmt']['active'] == true) { ?>selected="selected" <?php } ?> value="true"><?php echo $this->translate('Active');?></option>
                                                   <option <?php if (isset($this->data['settings']['tags']['wmt']['active']) && $this->data['settings']['tags']['wmt']['active'] == false) { ?>selected="selected"<?php } ?> value="false"><?php echo $this->translate('Inactive');?> </option>
                                                </select>
                                                <a href="#" class="popoverGAconfig" data-toggle="popover" data-placement="bottom" title="" data-content="<?php echo $this->translate("Toggles activities of Webmaster Tools ON and OFF. "); ?>"><i class="fa fa-info-circle"></i></a>
                                                <?php echo $this->errorMessages($this->errors['wmt_active']);?>
                                            </div>
                                            <div id="webMasterHide">
                                                <div class="configFormContainer wmt_metaContainer">
                                                    <label for="data[wmt_meta]"><?php echo $this->translate('Web Master Meta tag');?>:</label>
                                                    <a href="#" class="popoverGAconfig apsolute"  data-toggle="popover" data-placement="bottom" title="" data-content="<?php echo $this->translate("Allows Google to verify user's ownership over his web site. User can obtain his Meta Tag in Google's Webmaster Tools."); ?>"><i class="fa fa-info-circle"></i></a>
                                                    <textarea  id="data[wmt_meta]" class="wmt_meta" name="data[wmt_meta]" ><?php echo (isset($this->data['settings']['tags']['wmt']['meta']))?$this->escape($this->data['settings']['tags']['wmt']['meta']):"";?></textarea>
                                                    
                                                    <?php echo $this->errorMessages($this->errors['wmt_meta']);?>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                            </div>
                    </form>    
                </div>
            </div>
            <div>
                <div id="GTM"> <!-- Google tags -->
                    <div class="infoContainer">
                        <h2><?php echo $this->translate("Google Tag Manager ");?></h2>
                        <p><?php echo $this->translate("Google Manager is powerful free tool that allows user it self to update all the tags from site without editing site code. This reduces error, puts user in charge, and drastically reduces the time of dealing with tags. ");?></p>
                    </div>
                    <form method="post" class="hcms_form configForm " title="<?php echo $this->translate('Edit Configuration');?>" action="<?php echo $this->url(array('controller' => 'google-service', 'action' => 'edit')) ?>" enctype="application/x-www-form-urlencoded">
                            <div id="colist-1" class="collapslist ri h-tabs">
                                    <div class="content-holder">
                                        <div class="content">
                                            <div class="configFormContainer">
                                                <label for="data[gtm_active]"><?php echo $this->translate('Status');?>:</label>
                                                <select  id="data[gtm_active]" name="data[gtm_active]">
                                                   <option <?php if (isset($this->data['settings']['tags']['gtm']['active'] ) && $this->data['settings']['tags']['gtm']['active'] == true) { ?>selected="selected" <?php } ?> value="true"><?php echo $this->translate('Active');?></option>
                                                   <option <?php if (isset($this->data['settings']['tags']['gtm']['active']) && $this->data['settings']['tags']['gtm']['active'] == false) { ?>selected="selected"<?php } ?> value="false"><?php echo $this->translate('Inactive');?> </option>
                                                </select>
                                                <a href="#" class="popoverGAconfig" data-toggle="popover" data-placement="bottom" title="" data-content="<?php echo $this->translate("Toggles ON and OFF tag manager function on web site. "); ?>"><i class="fa fa-info-circle"></i></a>
                                                <?php echo $this->errorMessages($this->errors['gtm_active']);?>
                                            </div>
                                            <div id="tagManagerIdHide">
                                                <div class="configFormContainer">
                                                    <label for="data[container_id]"><?php echo $this->translate('Google Tag Manager Id');?>:</label>
                                                    <input type="text" size="30"  value="<?php echo (isset($this->data['settings']['tags']['gtm']['container_id']))?$this->escape($this->data['settings']['tags']['gtm']['container_id']):"";?>" id="data[container_id]" name="data[container_id]" maxlength="60"/>
                                                    <a href="#" class="popoverGAconfig" data-toggle="popover" data-placement="bottom" title="" data-content="<?php echo $this->translate("Google Tag Manager ID is the piece of code, that user gets when create Tag Manager account. It can be found in the list of containers in user's Google Tag Manager account, under 'ID' section. "); ?>"><i class="fa fa-info-circle"></i></a>
                                                    <?php echo $this->errorMessages($this->errors['container_id']);?>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                            </div>
                    </form>    
                    
                </div>
            </div>
            <div>
                <div id="Robots"> <!-- Allow / Disallow crowlers  -->
                    <div class="infoContainer">
                        <h2><?php echo $this->translate("Web Robots");?></h2>
                        <p><?php echo $this->translate("This operation makes your website to be visible or not, for Google's search. You can make content from your web site to be included in global Google's search for user from all around the world. ");?></p>
                    </div>
                    <form method="post" class="hcms_form configForm " title="<?php echo $this->translate('Edit Configuration');?>" action="<?php echo $this->url(array('controller' => 'google-service', 'action' => 'edit')) ?>" enctype="application/x-www-form-urlencoded">
                            <div id="colist-1" class="collapslist ri h-tabs">
                                    <div class="content-holder">
                                        <div class="content">
                                            <div class="configFormContainer">
                                                <label for="data[robots_active]"><?php echo $this->translate('Status');?>:</label>
                                                <select  id="data[robots_active]" name="data[robots_active]">
                                                   <option <?php if (isset($this->data['settings']['tags']['robots']['active'] ) && $this->data['settings']['tags']['robots']['active'] == true) { ?>selected="selected" <?php } ?> value="true"><?php echo $this->translate('Hidden for search engines');?></option>
                                                   <option <?php if (isset($this->data['settings']['tags']['robots']['active']) && $this->data['settings']['tags']['robots']['active'] == false) { ?>selected="selected"<?php } ?> value="false"><?php echo $this->translate('Visible for search engines');?> </option>
                                                </select>
                                                <a href="#" class="popoverGAconfig" data-toggle="popover" data-placement="bottom" title="" data-content="<?php echo $this->translate("Set 'Allow' to toggle ON, or 'Disallow' to toggle OFF this function. "); ?>"><i class="fa fa-info-circle"></i></a>
                                                <?php echo $this->errorMessages($this->errors['robots_active']);?>
                                            </div>
                                        </div>
                                    </div>
                            </div>
                    </form>    
                    
                </div>
            </div>

	</div>
    </div>
    
    <div>
        <button class="btn btn-primary submit" name="submit[save]" value="Save" type="button"><?php echo $this->translate('Save');?></button>
    </div>
</div>
<script type="text/javascript">
    var colist1 = $(".collapslist").collapsList({
        expand: function(e, ui) {
                //alert('On expand: ' + ui.context_obj);
              },
        collapse: function(e, ui) {
                //alert('On collapse: ' + ui.id);
              },
        showMore: function(e, ui) {
                //alert('On show more: ' + ui.id);
              },
        context_obj: 'Context OBJ'

    });
                
    $(".collapslist .heading").click(function () {
        $(this).find(".title i").toggleClass("icon-plus-small icon-minus-small");
    });
    
    $(document).ready(function(){
        
        //when inacive is selected hide properties
        
        var hide = $("#data\\[active\\]").val();
        if (hide == "false") {
            $("#hideSetingsSearch").addClass("hide");
        }
        $("#data\\[active\\]").on("change", function(){
            var status = $(this).val();
            if (status == "false") {
                $("#hideSetingsSearch").addClass("hide");
            } else if (status == "true") {
                $("#hideSetingsSearch").removeClass("hide");
            }
        });
        
        var hide = $("#data\\[ga_active\\]").val();
        if (hide == "false") {
            $("#GA-hide").addClass("hide");
        }
        $("#data\\[ga_active\\]").on("change", function(){
            var status = $(this).val();
            if (status == "false") {
                $("#GA-hide").addClass("hide");
            } else if (status == "true") {
                $("#GA-hide").removeClass("hide");
            }
        });
        
        
        var hide = $("#data\\[wmt_active\\]").val();
        if (hide == "false") {
            $("#webMasterHide").addClass("hide");
        }
        $("#data\\[wmt_active\\]").on("change", function(){
            var status = $(this).val();
            if (status == "false") {
                $("#webMasterHide").addClass("hide");
            } else if (status == "true") {
                $("#webMasterHide").removeClass("hide");
            }
        });
        
        var hide = $("#data\\[gtm_active\\]").val();
        if (hide == "false") {
            $("#tagManagerIdHide").addClass("hide");
        }
        $("#data\\[gtm_active\\]").on("change", function(){
            var status = $(this).val();
            if (status == "false") {
                $("#tagManagerIdHide").addClass("hide");
            } else if (status == "true") {
                $("#tagManagerIdHide").removeClass("hide");
            }
        });
        
        
          
    });
    
    
    
    $(function() {
	/*res-tables*/
        var rt = ".res-tabs";
        // initialize NaviBar (test version)
        $(rt).restabs({
            context_obj: this,
            responsiveMode: true,
            tabPlus: true,
            resizeTimeOut: 600,
            showRemove: true
        });
        // add end tab    
        
	/* Live color changer on preview part of google search */   
        
	$('.gsc-content input').each(function(){
	   var element = '.gpicker-cell .' + $(this).attr('class').split(" ")[1] + '';
	   var inputValue = 'input.' + $(this).attr('class').split(" ")[1] + '';
	   $(element).css("color", $(inputValue).val()); 
	});
	
	$('.gsc-content select').each(function(){
	    var element = '.gpicker-cell .' + $(this).attr('class') + '';
	    var option = 'select.' + $(this).attr('class') + '';
	    var optionVal = $(option).find(":selected").val();
	    $(element).css("fontSize", optionVal);
	});
	 
	$('.gsc-content input').on('change', function() {
	    var element = '.gpicker-cell .' + $(this).attr('class').split(" ")[1] + '';
	    var inputValue = 'input.' + $(this).attr('class').split(" ")[1] + '';
	    console.log(element);
	    $(element).css("color", $(inputValue).val());
	});

	$('.gsc-content select').on('change', function() {
	    var element = '.gpicker-cell .' + $(this).attr('class') + '';
	    var option = 'select.' + $(this).attr('class') + '';
	    var optionVal = $(option).find(":selected").val();
	    $(element).css("fontSize", optionVal);
	});
	
    });

</script>