<?php
    $this->headScript()->appendFile('/js/ajaxFormBS.js');
    $this->headScript()->appendFile('/plugins/hfb/js/jquery.hfbSelect.js');
    $this->headScript()->appendFile('/plugins/hfb/js/jquery.hfbSearch.js');
    $this->headScript()->appendFile('/plugins/hfb/js/jquery.hfbList.js');
    $this->headScript()->appendFile('/modules/teaser/js/teaser_list.js');
    $this->headScript()->appendFile('/plugins/serverbrowser/bs/jquery.filebrowserdialog.js');
    $this->headScript()->appendFile('/plugins/imagebrowser/bs/jquery.imagebrowserdialog.js');
    $this->headScript()->appendFile('/plugins/jquery-ui-timepicker-addon/jquery-ui-timepicker-addon.js');    
    
    //chosen
    $this->headScript()->appendFile('/plugins/chosen/chosen.jquery.min.js');
    $this->headLink()->appendStylesheet( '/plugins/chosen/chosen.css');
    //dd slick
    $this->headScript()->appendFile('/plugins/ddslick/jquery.ddslick.min.js');
    
    $this->headLink()->appendStylesheet( '/modules/teaser/css/teaser.css');    
    $this->headLink()->appendStylesheet('/modules/admin/css/file-menager.css');
    $boxes = Teaser_Model_TeaserMapper::getInstance()->getBox();
?>
<script type="text/javascript">    
    var picker = "<?php echo $this->picker; ?>",
        boxes = <?php echo json_encode($boxes); ?>,
        listUrl = '/' + CURR_LANG + '/teaser/admin-teaser/list/?langFilter=<?php echo $this->defaultLang;?>',
        deleteConfirmation = '<?php echo $this->translate('Are you sure you want to delete this record?');?>'; 
</script>

<div class="hcms_content_top">
    <h1><?php echo $this->translate('Sliders'); ?></h1>
</div>
<div class="hcms_content">
    <div class="article">
	<div class="hcms_btn_actions hcms_teaser">
	    <div class="btn-block teaser-block">
		<a href="#" class="add btn btn-small btn-primary"><?php echo $this->translate('Add new'); ?></a>
		<div class="hcms_input_block hcms_search">
		    <div class="input-group">
			<?php echo $this->cmsMenuSelect(array(
				'id'    => 'menu_item_id',
				'name'  => 'menu_item_id',
				'default_text'  => 'Choose menu item'
			));?>   
			<input type="text" class="_input" name="name" id="name" value="" placeholder="<?php echo $this->translate('Name');?>" maxlength="100" />
			<div class="input-group-btn"><a href="#" id="filter" class="btn btn-small btn-primary"><?php echo $this->translate('Filter');?></a></div>
		    </div>
		</div>
	    </div>
	    <div class="btn-block teaser-block">
		<?php if($this->singleLang === false) {?>
		<select id="langFilter" name="langFilter">
		   <?php echo $this->langOptions($this->languages,$this->defaultLang,true);?>
		</select>
		<?php }?>
		<select id="box_code" name="box_code">
			<option value="" selected="selected"><?php echo $this->translate('Choose Template');?></option>
			 <?php  foreach ($boxes as $boxCode => $box ) {?>
			<option value="<?php echo $boxCode ;?>" <?php if(isset($box['icon'])){ echo 'data-imagesrc="' . $box['icon'] . '"';};?> > <?php echo $box['name']; ?> </option> 
			<?php }?>
		</select>    
		<div class="btn-group date-group">
		    <input type="text" class="_input" name="start_dt" id="start_dt" value="" placeholder="<?php echo $this->translate('Start Date');?>" maxlength="100" />
		</div>
		<div class="btn-group date-group">
		    <input type="text" class="_input" name="end_dt" id="end_dt" value="" placeholder="<?php echo $this->translate('End Date');?>" maxlength="100" />
		</div>
	    </div>
	</div>
	<div class="teaserList" id="listContainer"></div>
	<div id="pager" class="pager"></div>
    </div>
</div>
<script type="text/html" id="records_tpl">
<%  if (rows.length > 0){
        for ( var j = 0; j < rows.length; j++ ){ %>
	<div class="collapslistHolder ">
	    <div id="colist-1" class="collapslist ri h-tabs" >
		<div class="article expanded">
		    <div class="heading">
			<h2 class="title"><i class="icon-minus-small"></i><%=rows[j].name %>(<%=rows[j].box_name %>)</h2>
		    </div>
		    <div class="content-holder">
			<ul>
			    <li><a href="#" class="btn itemAdd" data-box_code="<%=rows[j].box_code%>" data-id="<%=rows[j].id%>"><i class="fa fa-plus"></i><?php echo $this->translate('Add Item');?></a></li>
			    <li><a href="#" class="btn edit" data-id="<%=rows[j].id%>"><i class="fa fa-pencil"></i><?php echo $this->translate('Edit');?></a></li>
			    <li><a href="#" class="btn delete" data-id="<%=rows[j].id%>"><i class="fa fa-times"></i><?php echo $this->translate('Delete');?></a></li>
			    <li><a href="#" class="btn clone" data-id="<%=rows[j].id%>"><i class="fa fa-files-o"></i><?php echo $this->translate('Clone');?></a></li>
			    <li><a href="#" class="btn preview" data-id="<%=rows[j].id%>"><i class="fa fa-eye"></i><?php echo $this->translate('Preview');?></a></li>
			</ul>
			<div class="content">
			    <%  if(rows[j]['items'].length > 0) { %>
			    <table class="hcms_table itemList" width="100%" data-id="<%=rows[j].id%>">
				<tbody data-id="<%=rows[j].id%>">
				    <%
				    var items = rows[j]['items'];
				    for ( var k = 0; k < items.length; k++ ){ %>
				    <tr data-id="<%=items[k].id%>" data-teaser_id="<%=rows[j].id%>" data-status="<%=items[k].status%>">
					<td>
					    <%
					    var itemImage = getItemImage(items[k]);
					    if(itemImage){%>
					    <img src="<%=itemImage%>" alt="">
					    <%}%>
					</td>            
					<td class="fixed-width">
					    <%=items[k].title%><br>
					    <ul class="hcms_menu_actions">                                
						<li><a href="#" class="itemEdit" data-id="<%=items[k].id%>"  data-toggle="modal" data-target="#myModal"><span><?php echo $this->translate('Edit');?></span></a></li>
						<li><a href="#" class="itemClone" data-id="<%=items[k].id%>"><span><?php echo $this->translate('Clone');?></span></a></li>
						<li><a href="#" class="itemDelete" data-id="<%=items[k].id%>"><span><?php echo $this->translate('Delete');?></span></a></li>
					    </ul>
					</td>
					<td><%=items[k].start_dt%></td>
					<td><%=items[k].end_dt%></td>
					<td class="status_<%=items[k].status%>"><%=items[k].status_name%></td>
				    </tr>
				<%  } %>                         
				</tbody>
			    </table>
			    <%  } %>
			</div>
		    </div>
		</div>
	    </div>
	</div>
    <%  }
    } %>
</script>

<script type="text/html" id="images_tpl">
<%  if (images){
        for ( var imageId in images){
            var image = images[imageId];
            var imageValue = (data && data['content'] && data['content'][imageId])? data['content'][imageId]: '';%>    
	    <div class="btn-block">
		<label><%=image.name %></label>
		<div class="input-group">
		    <input type="text" class="_input customTeaserImage" data-id="<%=imageId %>" name="data[content][<%=imageId %>]"  id="data[content][<%=imageId %>]" value="<%=imageValue%>" maxlength="255" />
		    <div class="input-group-btn">
			<button class="btn btn-default btn-small browse" title="Browse" type="button">browse</button>
		    </div>        
		</div>
	    </div>
	    <!--    <label class="customImage"><%=image.name %>
		    <div class="customImage">
			<input type="text" class="_input customTeaserImage" data-id="<%=imageId %>" name="data[content][<%=imageId %>]"  id="data[content][<%=imageId %>]" value="<%=imageValue%>" maxlength="255" />
			<button class="btn btn-default btn-small browse" title="Browse" type="button">...</button>
		    </div>        
		</label>-->
<%      }
    } %>    
</script>

<div id="boxDialog" title="<?php echo $this->translate('Template');?>" style="display: none;">
    <div style="height: 400px">
        <select id="dialogBoxCode" name="dialogBoxCode">
            <option value="" selected="selected"><?php echo $this->translate('Choose Template');?></option>
                <?php  foreach ($boxes as $boxCode => $box ) {?>
                    <option value="<?php echo $boxCode ;?>" <?php if(isset($box['icon'])){ echo 'data-imagesrc="' . $box['icon'] . '"';};?> > <?php echo $box['name']; ?> </option> 
                <?php }?>
        </select>
    </div>
</div>

<div id="previewDialog" title="<?php echo $this->translate('Preview settings');?>" style="display: none">
    <label><?php echo $this->translate('Preview Date/Time');?></label>
    <div class="date-group">
	<input type="text" class="_input" name="preview_dt" id="preview_dt" value="" maxlength="100" />
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function(){
	var collapseTeaser = function(){
	    var colist1 = $(".collapslist").collapsList({
	    expand: function(e, ui) {
		    //alert('On expand: ' + ui.context_obj);
		  },
	    collapse: function(e, ui) {
		    //alert('On collapse: ' + ui.id);
		  },
	    showMore: function(e, ui) {
		    //alert('On show more: ' + ui.id);
		  },
	    context_obj: 'Context OBJ'
	    });

	    $(".collapslist .heading").click(function () {
		$(this).find(".title i").toggleClass("icon-plus-small icon-minus-small"); // toggle icon for collapslist
	    });
	}
	$('body').on('click', '.collapslist', collapseTeaser);	
    });

</script>