<div class="clearfix">
    <div class="left_content">
        <script type="text/javascript">
            $(document).ready(function(){
                $('body').addClass("<?php echo (strtolower($this->currentPage)); ?>");
            });
        </script>
        <?php
        $this->headLink()->appendStylesheet('/modules/gallery/css/album/style.css');
        $countPages = count($this->categories);
//        if (is_array($this->categories) && count($this->categories) > 0) {
            ?>
            <ul class="album_p_lists_holder">
                <?php
                /* @var $category Cms_Model_Category */
                foreach ($this->categories as $category) {
                    ?>
                    <li class="album_p_list">
                        <a href="<?php echo $this->url(array('module' => 'gallery', 'controller' => 'album', 'action' => 'index', 'category_id' => $category->get_id()), $this->route, true); ?>">
                            <div class="name_holder">
                                <h2><?php echo $this->escape($category->get_name()); ?></h2>
                            </div>
                        </a>
                    </li>
                <?php } ?>
            </ul>
            <?php
            $this->addScriptPath(APPLICATION_PATH . '/modules/cms/views/scripts/');
            if ($countPages < $this->paging['records']) {
                echo $this->paginationControl($this->paginator, 'Sliding', 'paginator.phtml', array('listingParams' => $this->listingParams));
            }
//        } else {
            //echo $this->translate('No albums found');
//        }
        ?>
    </div>
    <div class="right_content">
        <?php
        $this->addScriptPath(APPLICATION_PATH . '/modules/cms/views/scripts/');
        echo $this->partial('photo/list.phtml', array(
                                                                                'pages' => $this->pages,
                                                                                'paginator' => $this->paginator,
                                                                                'pagingPhotos' => $this->pagingPhotos,
                                                                                'route' => $this->route,
                                                                                'listingParams' => $this->listingParams,
                                                                                'fileWebRoot' => $this->fileWebRoot
                                                                    )
        );
        ?>
        <div class="link_back_holder">
            <?php if(isset($this->level) && $this->level == 0) {?>
            <a href="<?php echo $this->url(array('module'=>'gallery','controller'=>'album','action'=>'list'),$this->route,true);?>"><?php echo $this->translate('Back') ?></a>
            <?php } elseif (isset($this->level) && $this->level > 0) {?>
            <a href="<?php echo $this->url(array('module'=>'gallery','controller'=>'album','action'=>'index','category_id'=>$this->parentId),$this->route,true);?>"><?php echo $this->translate('Back') ?></a>
            <?php }?>
        </div>
    </div>
</div>
