<script type="text/javascript">
    $(document).ready(function(){
        $('body').addClass("<?php echo (strtolower($this->currentPage));  ?>");
    });
</script>
<?php
$this->headLink()->appendStylesheet( '/modules/gallery/css/album/style.css');
$countPages = count($this->categories);
if(is_array($this->categories) && count($this->categories) > 0){
?>
<!--<form method="post" action="<?php //echo $this->url(array('module'=>'store','controller'=>'page','action'=>'search'), $this->route, true);?>">
    <div class="search_field">
        <input type="text" name="search" value="<?php //echo $this->search ?>" />
        <input type="submit" id="submit" name="submit" value="Search">
    </div>
</form>-->
<ul class="album_lists_holder">
<?php
/* @var $category Cms_Model_Category */
    foreach ($this->categories as $category) {
    ?>
        <li class="album_list">
            <a href="<?php echo $this->url(array('module'=>'gallery','controller'=>'album','action'=>'index','category_id'=>$category->get_id()),$this->route,true);?>">
                <?php
                    $picture = $category->get_data('picture');
                    if (isset($picture) && $picture !== '') {
                ?>
                <div class="image_holder">
                    <img src="<?php echo $this->fileWebRoot.$picture; ?>" alt="Category Picture" width="175" height="200" />
                </div>
                <?php }?>
                <div class="name_holder">
                    <h2><?php echo $this->escape($category->get_name());?></h2>
                </div>
            </a>
            <div class="album_description"><p><?php echo $category->get_description(); ?></p></div>
        </li>
   <?php } ?>
</ul>
<?php
    $this->addScriptPath(APPLICATION_PATH . '/modules/cms/views/scripts/');
    if ($countPages < $this->paging['records']) {
        echo $this->paginationControl($this->paginator,'Sliding','paginator.phtml',array('listingParams'=>$this->listingParams));
    }
} else {
    echo $this->translate('No albums found');
}
?>