<?php
    $this->menuItemId = 1;
    $this->headScript()->appendFile('/plugins/collapsibleBox/jquery.collapsibleBox.js');
    $this->headScript()->appendScript('$(window).load(function(){
        $(".collapse").collapsibleBox({
            handleSelector: ".collapseHandle",
            collapsibleSelector: ".collapseBox",
            openClass: "open",
            closedClass: "closed",
            onChange: function(el, closed){
               //console.log(el, "is closed: ", closed);
            },
            getIsClosed: function(widget){
                var height = widget.$el.height();
                //console.log("heights",widget.$el.find("img").outerHeight(true), widget.$el.find(".teaserItemHeading").outerHeight(true), widget.$el.find("p").outerHeight(true), widget.$el.find("a.horisenBtn").outerHeight(true));
                var elementsHeight = widget.$el.find("img").outerHeight(true) + widget.$el.find(".teaserItemHeading").outerHeight(true) + widget.$el.find("p").outerHeight(true) + widget.$el.find("a.horisenBtn").outerHeight(true);
                var closed = elementsHeight > height;
                if(!closed){
                    //remove toogle button
                    widget.$el.find("h2.collapseHandle i").remove();
                }
                return {
                    "closed": closed,
                    "toggable": closed 
                };
            }            
        });        
    })');
?>
<div class="introTxt">
    <h1>Cross-media marketing solutions</h1>
    <h2>Tailored to your needs</h2>
</div>
<p>Choose a smart combination of services and web applications from HORISEN cloud-based software<br /> which will leverage your company in both analogue and digital business communications world.</p>
