<script type="text/javascript">
    $(document).ready(function(){
       $(".video_link").click(function() {
           $.fancybox({
                padding: 0,
                'autoScale'     : false,
                'transitionIn'  : 'elastic',
                'transitionOut' : 'elastic',
                'title'         : this.title,
                'width'         : 795,
                'height'        : 447,
                'href'          : this.href.replace(new RegExp("watch.*v=","i"), "v/"),
                'type'          : 'swf',
                'swf'           : {
                    'allowfullscreen'   : 'true'
                 }
            });
            return false;
       });
    });
</script>
<div class="pageContentHolder eleven columns">
<h1><?php echo $this->translate("Videos"); ?></h1>
<p>
    <?php echo $this->translate('Videos intro text'); ?>
</p>
<hr />
<?php if (count($this->paginator) > 0):?>
<div class="clearfix">
<ul>
<?php foreach ($this->paginator as $video):
   if($video['error'] == ''){ ?>
  <li style="list-style-type: none;float:left;">
      <div style="width:505px;height:200px;float:left;">
            <div style="float:left;padding-right: 20px;height:180px;">
               <a class="video_link" href="<?php echo $video['videowatchpage']; ?>" ><img  alt="" src="<?php echo $video['thumbnail'];?>" /></a>
            </div>
            <p style="margin-left:140px;">
                <?php if($this->show_title == "yes"){ ?><strong>Title: </strong><?php echo $video['title'];} ?>
            </p>
            <p style="margin-top:5px;margin-left: 140px;">
                <?php if($this->show_duration == "yes"){ ?><strong>Duration: </strong><?php echo $video['duration'] . " sec";}?>
            </p>
            <p style="margin-top:5px;margin-left: 140px;">
                <?php if($this->show_views == "yes"){ ?><strong>Views: </strong><?php echo $video['viewcount'];}?>
            </p>
            <p style="margin-top:5px;margin-left: 140px;">
                <?php
                    $url_ready = preg_replace('/(http[s]?:\/\/[^\s]*)/i', '<a href="$1" target="_blank">$1</a>', $video['description']);
                    if($this->show_desc == "yes"){ ?>
                    <strong>Description: </strong><?php echo $this->escape($this->abbreviate($url_ready, 140));?>
                    <?php  }?>
            </p>
            <a href="<?php echo $video['videowatchpage']; ?>" target="_blank" class="more" style="width:150px;padding-top:5px;">&raquo; <?php echo $this->translate('Watch on YouTube');?></a>

      </div>
      <hr />
  </li>
<?php }else{
        echo $video['error'] . "<br>";

    }
    endforeach; ?>
</ul>
</div>
<div class="clearfix"></div>
<?php
    $this->addScriptPath(APPLICATION_PATH . '/modules/cms/views/scripts/');
    echo $this->paginationControl($this->paginator,'Sliding','paginator.phtml',array('route'=>$this->route, 'listingParams'=>$this->listingParams));
    else:    echo $this->translate('No Youtube Videos are available.');
 ?>
<?php endif; ?>
</div>
<div class="rightSideContent six columns ">
    <div class="socialSideContainer">
        <nav class="socialSide">
            <a href="#" class="facebook"></a>
            <a href="#" class="twitter"></a>
            <a href="#" class="google"></a>
            <a href="#" class="soc1"></a>
            <a href="#" class="linkedIn"></a>
            <a href="#" class="soc2"></a>
            <a href="#" class="soc3"></a>
        </nav> 
    </div>
</div>