<?php
$this->headScript()->appendFile('/plugins/hfb/js/jquery.hfbSelect.js');
$this->headScript()->appendFile('/plugins/hfb/js/jquery.hfbSearch.js');
$this->headScript()->appendFile('/plugins/hfb/js/jquery.hfbList.js');
$this->headScript()->appendFile('/modules/admin/js/list.js');
$this->headScript()->appendFile('/plugins/jqueryui/i18n/jquery.ui.datepicker-' . $this->lang .'.js');
?>
<script type="text/javascript">
    var formId = '<?php echo $this->formId; ?>';
    initList('/' + CURR_LANG + '/contact/admin-generic/contact-list/form_id/' + formId,{},function(me,data){
        //DELETE ajax action call
        $("#listContainer").find("a.delete").click(function(){
            if(!window.confirm("<?php echo $this->translate('Are you sure you want to delete this contact?\nThis operation has no undo.');?>")){
                return false;
            }
            $.ajax({
                type: "POST",
                data: {"contact_id":$(this).data('id')},
                url: '/' + CURR_LANG + '/' + 'contact/admin-generic/contact-delete/form_id/' + formId,
                success: function(data) {
                    if(data['success']){
                        if(data['message']){
                            $.flashMessenger(data['message'],{clsName:"ok"});
                        }
                        //reload list
                        updateList();
                    }
                    else{
                        if(data['message']){
                            $.flashMessenger(data['message'],{clsName:"err"});
                        }
                    }
                },
                error: function(data) {
                    alert(_('An error has occured retrieving data!'));
                }
            })
            return false;
        });
         $("#listContainer").find("a.show_more").click(function(){
            $("#show-more-dialog").html(nl2br($(this).data('text')));
            $("#show-more-dialog").dialog({modal:true});
         });
    });

   

    //init select filter
    $(document).ready(function(){

        $("#langFilter").change(function(){
            updateList('langFilter',$(this).val());
        });

        $("#all_export").click(function(){
            $('#form_contact').submit();
            return false;
        });

        var dates = $( "#fromFilter, #toFilter" ).datepicker({
            dateFormat: 'dd.mm.yy',
            autoSize: true,
            defaultDate: "+1w",
            changeMonth: true,
            numberOfMonths: 1,
            onSelect: function( selectedDate ) {
                var option = this.id == "fromFilter" ? "minDate" : "maxDate",
                instance = $( this ).data( "datepicker" ),
                date = $.datepicker.parseDate(
                instance.settings.dateFormat ||
                    $.datepicker._defaults.dateFormat,
                selectedDate, instance.settings );
                dates.not( this ).datepicker( "option", option, date );
                if(this.id == 'fromFilter'){
                    updateList('fromFilter', $('#fromFilter').val());
                }else{
                    updateList('toFilter', $('#toFilter').val());
                }
            }
        });

        $("#fromFilter").bind('keyup' ,function(){
            if($(this).val() != ""){
                updateList('fromFilter', $('#fromFilter').val());
            }
        });

        $("#toFilter").bind('keyup' ,function(){
            if($(this).val() != ""){
                updateList('toFilter', $('#toFilter').val());
            }
        });

        $("#from_delete").click(function(){
            if($('#fromFilter').val() != ""){
                $('#fromFilter').val("");
                updateList('fromFilter', $('#fromFilter').val());
            }
        });

        $("#to_delete").click(function(){
            if($('#toFilter').val() != ""){
                $('#toFilter').val("");
                updateList('toFilter', $('#toFilter').val());
            }
        });
        


});

</script>
<form id="form_contact" name="form_contact" action="/<?php echo $this->currLang; ?>/contact/admin-generic/export/form_id/<?php echo $this->formId;?>">
    <div class="hcms_content_top">
        <h1><?php echo $this->translate('Contacts'); ?></h1>
    </div>
    <div class="hcms_content">
	<div class="hcms_btn_actions">
	    <div class="btn-block ">
		<a id="all_export" href="#" class="add btn btn-small btn-primary"><?php echo $this->translate('Export'); ?></a>
		<div class="hcms_input_block hcms_search">
		    <input id="searchFilter" name="searchFilter" type="text" value="" />
		    <a href="#" id="searchExecute" class="btn btn-small btn-primary"><?php echo $this->translate("Search"); ?></a>
		</div>
	    </div>
	    <div class="btn-block">
		    <?php if($this->singleLang === false){?>
		    <select id="langFilter" name="langFilter">
			<?php echo $this->langOptions($this->languages,$this->defaultLang,true);?>
		    </select>
		    <?php }?>
		    <div class="btn-group date-group">
			<input id="fromFilter" name="fromFilter" type="text" placeholder="<?php echo $this->translate('From date'); ?>" readonly/>
			<i id="from_delete" class="fa fa-times delete_from_to"></i>
			<!--<span id="from_delete" class="delete_from_to"></span>-->
		    </div>
		    <div class="btn-group date-group">
			<input id="toFilter" name="toFilter" type="text" placeholder="<?php echo $this->translate('To date'); ?>" readonly/>
			<i id="to_delete" class="fa fa-times delete_from_to"></i>
			<!--<span id="to_delete" class="delete_from_to"></span>-->
		    </div>
	    </div>
	</div>
	<div class="hcms_scroll_table">
	    <table class="hcms_table adminList" width="100%">
		<thead>
		    <tr>
<?php
foreach ($this->columns as $columnId => $column) {
?>
                        <th><a href="#" class="sort" data-column="<?php echo $columnId;?>"><?php echo $this->translate($column['name']); ?><b></b></a></th>
<?php                          
}
?>
		    </tr>
		</thead>
		<tbody id="listContainer">
		</tbody>
	    </table>
	</div>
        <div id="pager" class="pager"></div>
    </div>
</form>
<script type="text/html" id="records_tpl">
    <% if (rows.length > 0){
    var rowClass = 'odd';
    %>
    <% for ( var i = 0; i < rows.length; i++ ){
    rowClass = (i % 2 == 0)? 'even':'odd';
    %>
    <tr class="<%=rowClass%>">
<?php

foreach ($this->columns as $columnId => $column) {
    if(isset($column['type']) && in_array($column['type'], array('message','textarea'))){
?>   
        <td><a class="show_more" data-id="<%=rows[i].id%>" href="javascript:void(0);" data-text="<% print(escapeHtml(rows[i].<?php echo $columnId;?>));%>"><% print(escapeHtml(rows[i].<?php echo $columnId;?>_short));%></a></td>
<?php        continue;
    }
?>
        <td>
            <% print(escapeHtml(rows[i].<?php echo $columnId;?>));%>
<?php
    if($columnId == 'first_name'){
?>
            <ul class="hcms_menu_actions">
                <li><a href="#" class="delete" data-id="<%=rows[i].id%>"><?php echo $this->translate('Delete');?></a></li>
            </ul>            
<?php
    }
?>
        </td>
<?php
}
?>
    </tr>
    <% } %>
    <% } %>
</script>

<div id="show-more-dialog" style="display: none"></div>