<?php 

/***
 * TO DO
 * - multi upload yes/no
 * - progres bar yes/no
 * 
 */
//$this->headLink()->prependStylesheet('/plugins/jqueryFileUpload/css/jquery.fileupload.css');
$this->headScript()->appendFile('/plugins/jqueryFileUpload/js/vendor/jquery.ui.widget.js');
$this->headScript()->appendFile('/plugins/jqueryFileUpload/js/jquery.iframe-transport.js');
$this->headScript()->appendFile('/plugins/jqueryFileUpload/js/jquery.fileupload.js');
$this->headScript()->appendFile('/modules/contact/js/fileField.js');

$classes = isset($this->field['css_class'])? $this->field['css_class']: 'form-group col-sm-6 col-xs-12';
$extensions = '';
foreach($this->field['params']['extensions'] as $k => $ext){
    $extensions .= '.'.$ext.',';
}

?>
<link rel="stylesheet" type="text/css" href="/plugins/jqueryFileUpload/css/jquery.fileupload.css">
<div id="field-<?php echo $this->fieldId; ?>"  class="<?php echo $classes;?>">
    <input type="hidden" name="data[<?php echo $this->fieldId; ?>]" id="hidden-<?php echo $this->fieldId; ?>"  value="" class="form-control <?php echo $this->errorMessages($this->errors, 'error', $this->fieldId, true);?>">
    <label for="data[<?php echo $this->fieldId; ?>]"><?php echo $this->translate($this->field['name']);?> <?php if(isset($this->field['required']) && $this->field['required']){echo '*';}?></label>
    <div class="input-group">
      <div class="pathBox">
          <span id="files-<?php echo $this->fieldId; ?>" name="data[<?php echo $this->fieldId; ?>]" class="filePath files-<?php echo $this->fieldId; ?>"><?php echo $this->translate($this->field['placeholder']);?></span>
      </div>
      <span class="input-group-btn">
        <span class="btn btn-default fileinput-button browse" id="<?php echo $this->fieldId; ?>">
            <i class="fa fa-paperclip"></i>
            <input id="file-<?php echo $this->fieldId; ?>" class="file-uploader" type="file" name="<?php echo $this->fieldId; ?>" accept="<?php echo $extensions; ?>" data-field_id="<?php echo $this->fieldId; ?>" data-form_data='{"form_id": "<?php echo $this->formId; ?>", "field_id": "<?php echo $this->fieldId; ?>"}' data-url="/<?php echo CURR_LANG; ?>/contact/file-upload/upload">
        </span>
          <a class="btn btn-default clear" id="clear-file-upload-<?php echo $this->fieldId; ?>" style="display: none;"><i class="fa fa-times"></i></a>
      </span>
    </div><!-- /input-group -->
</div><!-- /.col-lg-6 -->