<?php
$this->headScript()->appendFile('/plugins/hfb/js/jquery.hfbSelect.js');
$this->headScript()->appendFile('/plugins/hfb/js/jquery.hfbSearch.js');
$this->headScript()->appendFile('/plugins/hfb/js/jquery.hfbList.js');
$this->headScript()->appendFile('/modules/admin/js/list.js');
$this->headScript()->appendFile('/plugins/jqueryui/i18n/jquery.ui.datepicker-' . $this->lang .'.js');
?>
<script type="text/javascript">

    initList('/' + CURR_LANG + '/contact/admin/contact-list/',{},function(me,data){
        //DELETE ajax action call
        $("#listContainer").find("a.delete").click(function(){
            if(!window.confirm("<?php echo $this->translate('Are you sure you want to delete this contact?\nThis operation has no undo.');?>")){
                return false;
            }
            $.ajax({
                type: "POST",
                data: {"contact_id":$(this).data('id')},
                url: '/' + CURR_LANG + '/' + 'contact/admin/contact-delete',
                success: function(data) {
                    if(data['success']){
                        if(data['message']){
                            $.flashMessenger(data['message'],{clsName:"ok"});
                        }
                        //reload list
                        updateList();
                    }
                    else{
                        if(data['message']){
                            $.flashMessenger(data['message'],{clsName:"err"});
                        }
                    }
                },
                error: function(data) {
                    alert(_('An error has occured retrieving data!'));
                }
            })
            return false;
        });
         $("#listContainer").find("a.show_more").click(function(){
            $("#show-more-dialog").html(nl2br($(this).data('text')));
            $("#show-more-dialog").dialog({modal:true});
         });
    });

   

    //init select filter
    $(document).ready(function(){

        $("#langFilter").change(function(){
            updateList('langFilter',$(this).val());
        });

        $('#searchExecute').click(function() {
            updateList('searchFilter', $('#searchFilter').val());
        });

        $("#all_export").click(function(){
            $('#form_contact').submit();
            return false;
        });

        var dates = $( "#fromFilter, #toFilter" ).datepicker({
            dateFormat: 'dd.mm.yy',
            autoSize: true,
            defaultDate: "+1w",
            changeMonth: true,
            numberOfMonths: 1,
            onSelect: function( selectedDate ) {
                var option = this.id == "fromFilter" ? "minDate" : "maxDate",
                instance = $( this ).data( "datepicker" ),
                date = $.datepicker.parseDate(
                instance.settings.dateFormat ||
                    $.datepicker._defaults.dateFormat,
                selectedDate, instance.settings );
                dates.not( this ).datepicker( "option", option, date );
                if(this.id == 'fromFilter'){
                    updateList('fromFilter', $('#fromFilter').val());
                }else{
                    updateList('toFilter', $('#toFilter').val());
                }
            }
        });

        $("#fromFilter").bind('keyup' ,function(){
            if($(this).val() != ""){
                updateList('fromFilter', $('#fromFilter').val());
            }
        });

        $("#toFilter").bind('keyup' ,function(){
            if($(this).val() != ""){
                updateList('toFilter', $('#toFilter').val());
            }
        });

        $("#from_delete").click(function(){
            if($('#fromFilter').val() != ""){
                $('#fromFilter').val("");
                updateList('fromFilter', $('#fromFilter').val());
            }
        });

        $("#to_delete").click(function(){
            if($('#toFilter').val() != ""){
                $('#toFilter').val("");
                updateList('toFilter', $('#toFilter').val());
            }
        });
        


});

</script>
<form id="form_contact" name="form_contact" action="/<?php echo $this->currLang; ?>/contact/admin/export">
    <div class="hcms_content_top">
        <h1><?php echo $this->translate('Contacts'); ?></h1>
    </div>
    <div class="hcms_content">
	<div class="hcms_btn_actions">
	    <div class="btn-block ">
		<a id="all_export" href="#" class="add btn btn-small btn-primary"><?php echo $this->translate('Export'); ?></a>
		<div class="hcms_search">
		    <div class="input-group">
			<input id="searchFilter" name="searchFilter" type="text" value="" />
			<div class="input-group-btn">
			    <a href="#" id="searchExecute" class="btn btn-small btn-primary"><?php echo $this->translate("Search"); ?></a>
			</div>
		    </div>
		</div>
	    </div>
	    <div class="btn-block">
		    <?php if($this->singleLang === false){?>
		    <select id="langFilter" name="langFilter">
			<?php echo $this->langOptions($this->languages,$this->defaultLang,true);?>
		    </select>
		    <?php }?>
		    <div class="btn-group date-group">
			<input id="fromFilter" name="fromFilter" type="text" value="<?php echo $this->translate('From date'); ?>" readonly/>
			<i id="from_delete" class="fa fa-times delete_from_to"></i>
			<!--<span id="from_delete" class="delete_from_to"></span>-->
		    </div>
		    <div class="btn-group date-group">
			<input id="toFilter" name="toFilter" type="text" value="<?php echo $this->translate('To date'); ?>" readonly/>
			<i id="to_delete" class="fa fa-times delete_from_to"></i>
			<!--<span id="to_delete" class="delete_from_to"></span>-->
		    </div>
	    </div>
	</div>
	<div class="hcms_scroll_table">
	    <table class="hcms_table adminList" width="100%">
		<thead>
		    <tr>
			<th><a href="#" class="sort" data-column="gender"><?php echo $this->translate('Gender'); ?><b></b></a></th>
			<th><a href="#" class="sort" data-column="first_name"><?php echo $this->translate('First Name'); ?><b></b></a></th>
			<th><a href="#" class="sort" data-column="last_name"><?php echo $this->translate('Last Name'); ?><b></b></a></th>
			<th><a href="#" class="sort" data-column="street"><?php echo $this->translate('Street/Nr'); ?><b></b></a></th>
			<th><a href="#" class="sort" data-column="zip"><?php echo $this->translate('ZIP'); ?><b></b></a></th>
			<th><a href="#" class="sort" data-column="zip"><?php echo $this->translate('City'); ?><b></b></a></th>
			<th><a href="#" class="sort" data-column="country"><?php echo $this->translate('Country'); ?><b></b></a></th>
			<th><a href="#" class="sort" data-column="phone"><?php echo $this->translate('Phone'); ?><b></b></a></th>
			<th><a href="#" class="sort" data-column="mobile"><?php echo $this->translate('Mobile'); ?><b></b></a></th>
			<th><a href="#" class="sort" data-column="fax"><?php echo $this->translate('Fax'); ?><b></b></a></th>
			<th><a href="#" class="sort" data-column="email"><?php echo $this->translate('Email'); ?><b></b></a></th>
			<th><a href="#" class="sort" data-column="description"><?php echo $this->translate('Description'); ?><b></b></a></th>
			<th><a href="#" class="sort" data-column="message"><?php echo $this->translate('Message'); ?><b></b></a></th>
			<th><a href="#" class="sort" data-column="language"><?php echo $this->translate('Language'); ?><b></b></a></th>
			<th><a href="#" class="sort" data-column="posted"><?php echo $this->translate('Posted'); ?><b></b></a></th>
		    </tr>
		</thead>
		<tbody id="listContainer">
		</tbody>
	    </table>
	</div>
        <div id="pager" class="pager"></div>
    </div>
</form>
<script type="text/html" id="records_tpl">
    <% if (rows.length > 0){
    var rowClass = 'odd';
    %>
    <% for ( var i = 0; i < rows.length; i++ ){
    rowClass = (i % 2 == 0)? 'even':'odd';
    %>
    <tr class="<%=rowClass%>">
        <td>
           <%=rows[i].gender%>
        </td>
        <td>
            <%=rows[i].first_name%>
            <ul class="hcms_menu_actions">
             <li><a href="#" class="delete" data-id="<%=rows[i].id%>" data-type_id="<%=rows[i].type_id%>"><span><?php echo $this->translate('Delete');?></span></a></li>
            </ul>
        </td>
        <td><% print(escapeHtml(rows[i].last_name));%></td>       
        <td><% print(escapeHtml(rows[i].street));%></td>
        <td><% print(escapeHtml(rows[i].zip));%></td>
        <td><% print(escapeHtml(rows[i].city));%></td>
        <td><% print(escapeHtml(rows[i].country));%></td>
        <td><% print(escapeHtml(rows[i].phone));%></td>
        <td><% print(escapeHtml(rows[i].mobile));%></td>
        <td><% print(escapeHtml(rows[i].fax));%></td>
        <td><% print(escapeHtml(rows[i].email));%></td>
        <td><a class="show_more" data-id="<%=rows[i].id%>" href="javascript:void(0);" data-text="<% print(escapeHtml(rows[i].description));%>"><% print(escapeHtml(rows[i].description_short));%></a></td>
        <td><a class="show_more" data-id="<%=rows[i].id%>" href="javascript:void(0);" data-text="<% print(escapeHtml(rows[i].message));%>"><% print(escapeHtml(rows[i].message_short));%></a></td>        
        <td><% print(escapeHtml(rows[i].language));%></td>
        <td><% print(escapeHtml(rows[i].posted));%></td>
    </tr>
    <% } %>
    <% } %>
</script>

<div id="show-more-dialog" style="display: none"></div>
