<script>
$(function(){
    $('#carousel').bxSlider({
        pager: true
    });
  
    $("a.fBox").fancybox({
        'transitionIn'	:	'fade',
        'transitionOut'	:	'fade',
        'speedIn'		:	600, 
        'speedOut'		:	200, 
        'overlayShow'	:	false
    });
    
    $("a.fBox_prev").fancybox({
        'transitionIn'	:	'fade',
        'transitionOut'	:	'fade',
        'speedIn'		:	600, 
        'speedOut'		:	200, 
        'overlayShow'	:	false
    });
  
});
</script>
<div class="pageContentHolder eleven columns">
<article class="event-single">
    
    <h1><?php echo $this->escape($this->page->get_title());?></h1>
    <br />
    <p><?php echo $this->translate('Event intro text');?></p>
    <hr />
    <!--<div id="event-carousel">
            <ul id="carousel" class="event-slider">
              <?php 
                $i = 0;
                foreach($this->items as $ik => $item){ ?>
              <?php if($i%4 == 0) echo "<li>"; ?>
                <a class="fBox" rel="fBox" title="<?php echo $item->get_description(); ?>" href="/content/1/<?php $tmp = $item->get_data(); echo $tmp['image_url']; ?>"><img src="/content/1/<?php $tmp = $item->get_data(); echo $tmp['thumbnail_url']; ?>" alt="" /></a>
             <?php if(($i+1)%4 == 0) echo "</li>"; ?>
              <?php 
                $i++;
                }
              ?>
            </ul>
        </div>-->
    <section>
        <?php if ($this->page->get_data('image') != ''){ ?>
        <a class="fBox_prev" rel="fBox_prev" title="<?php echo $this->page->get_title(); ?>" href="/content/1/<?php echo $this->page->get_data('image_preview'); ?>"> <img src="<?php echo $this->escape($this->page->get_data('image'));?>" /> </a>
        <?php } ?>
       
        <div class="description">
            <h2><?php echo($this->escape($this->formatDate($this->page->get_extension()->get_start_date())));?></h2>
            <p><?php echo $this->page->get_content();?></p>
            <p></p>
            <?php if (isset($this->items) && count($this->items)){ ?>
             
            <?php } ?>
        </div>
    </section>
    <footer>
        <a class="more" href="<?php echo $this->url(array('module'=>'event','controller'=>'page','action'=>'list', 'timeline' => $this->timeline), 'cms', true);?>"><?php echo $this->translate('Back');?></a>
    </footer>
</article>
    <hr />
</div>
<div class="rightSideContent six columns ">
    <div class="socialSideContainer">
        <nav class="socialSide">
            <a href="#" class="facebook"></a>
            <a href="#" class="twitter"></a>
            <a href="#" class="google"></a>
            <a href="#" class="soc1"></a>
            <a href="#" class="linkedIn"></a>
            <a href="#" class="soc2"></a>
            <a href="#" class="soc3"></a>
        </nav> 
    </div>
</div>