<?php
     $this->headLink()->appendStylesheet("/modules/gallery/css/photo/listStyle.css");
     $this->headLink()->appendStylesheet("/plugins/fancybox/jquery.fancybox-1.3.4.css");
     $this->headScript()->appendFile('/plugins/fancybox/jquery.fancybox-1.3.4.js');
    //Zend_Debug::dump($this->paging);
    //Zend_Debug::dump($this->pages);
    if(count($this->pages) > 0){
?>
<script type="text/javascript">
    $(document).ready(function(){
        $("a.image_group").fancybox({
            'transitionIn'	:	'elastic',
            'transitionOut'	:	'elastic',
            'speedIn'          :600, 
            'speedOut'	:200,
            'showNavArrows': true
        });
    })
</script>
<ul class="photos_holder">
<?php
/* @var $page Cms_Model_Page */
foreach ($this->pages as $page) {
?>
    <li class="photo_list">
        <a class="image_group" href="<?php echo $this->fileWebRoot.$page->get_data('picture'); ?>" rel="group">
            <div class="photo">
                    <?php echo $this->image('name', $this->fileWebRoot.$page->get_data('picture'), array('alt' => 'image'), 'thumbnail'); ?>
            </div>
            <span><?php echo $page->get_title();?></span>
        </a>
    </li>
<?php
}
?>
</ul>
<?php
    $this->addScriptPath(APPLICATION_PATH . '/modules/cms/views/scripts/');
    echo $this->paginationControl($this->paginator,'Sliding','paginator.phtml',array('route'=>$this->route,'listingParams'=>$this->listingParams));
}
else{
    echo $this->translate('No photos found');
}