<?php
    $this->headScript()->appendFile('/plugins/hfb/js/jquery.hfbSelect.js');
    $this->headScript()->appendFile('/plugins/hfb/js/jquery.hfbSearch.js');
    $this->headScript()->appendFile('/plugins/hfb/js/jquery.hfbList.js');
    $this->headScript()->appendFile('/modules/auth/js/list.js');
    $this->headScript()->appendFile('/plugins/imagebrowser/bs/jquery.imagebrowserdialog.js');
?>
<script type="text/javascript">
    function getEditUrl(id){
        //console.log("test url");
        //console.log(sprintf('/%s/auth/admin-user/user-edit/id/%d',CURR_LANG,id));
        return sprintf('/%s/auth/admin-user/user-edit/id/%d',CURR_LANG,id);
    }
    function getDeleteUrl(id){
        return sprintf('/%s/auth/admin-user/user-delete/id/%d',CURR_LANG,id);
    }

    initList('/' + CURR_LANG + '/auth/admin-user/user-list/',{},function(me,data){
        $("#listContainer").find("a.delete").click(function(){
             if(confirm("<?php echo $this->translate('Are you sure you want to delete this User');?>?")){
                $.get(getDeleteUrl($(this).data('id')), function(result){
                    if(result["success"]){
                        $.flashMessenger(result['message'],{clsName:"ok"});
                        $("#listContainer").hfbList();
                    }
                    else{
                        $.flashMessenger(result['message'],{
                            autoClose:false,
                            modal:true,
                            clsName:"err"
                        });
                    }
                });
            }
            return false;
        });
    });
    //init select filter
    $(document).ready(function(){
        $("#langFilter").change(function(){
            updateList('langFilter',$(this).val());
        });
        $("body").on("updateList", function(){
            updateList();
        });
        $("#filter").click(function(){
            var params = $("#listContainer").data('params');
            params['username'] = $('#username').val();
            params['firstLastName'] = $('#firstLastName').val();
            params['email'] = $('#email').val();
            params['status'] = $('#status').val();
            params['role_id'] = $('#role_id').val();
           $("#listContainer").hfbList({
                'params': params
            });
            return false;
        })
       /* $(".add").click(function(){
            editDialog(null);
            return false;
        });*/
    });
</script>
<div class="hcms_content_top">
    <h1><?php echo $this->translate('Users'); ?></h1>
</div>
<div class="hcms_content">
    <div class="res-tabs">
        <ul class="tab-list">
            <li class="styled-apps"><?php echo $this->translate('List ');?></li>
        </ul>
        <div class="articles"> 
            <div>
                <div class="hcms_btn_actions users">
                    <div class="btn-block">
			<a href="#" class="add btn btn-small btn-primary"><i class="icon-plus-med"></i><?php echo $this->translate('Add new'); ?></a>
			<div class="hcms_input_block hcms_search">
			    <div class="input-group">
				<input name="searchFilter" id="searchFilter" type="text" value="" />
				<div class="input-group-btn">
				    <a href="#" class="btn btn-small btn-primary" id="searchExecute"><?php echo $this->translate("Search"); ?></a>
				</div>
			    </div>
			</div>
                    </div>
                    <div class="btn-block">
                        <input type="text" name="username" id="username" value="" maxlength="100" placeholder="Username"/>

                        <input type="text" name="firstLastName" id="firstLastName" value="" maxlength="100" placeholder="First or last name"/>

                        <input type="text" name="email" id="email" value="" maxlength="100" placeholder="Email address:"/>
                    </div>
                    <div class="btn-block hcms_input_block">
                        <select id="status" name="status">
                            <option value="" selected="selected"><?php echo $this->translate('Choose Status');?></option>
                            <option value="active"><?php echo $this->translate('Active');?></option>
                            <option value="blocked"><?php echo $this->translate('Blocked');?></option>
                            <option value="pending"><?php echo $this->translate('Pending');?></option>
                        </select>

                        <select id="role_id" name="role_id">
                            <option value="" selected="selected"><?php echo $this->translate('Choose Role');?></option>
                             <?php  foreach ($this->roles as $role ) {?>
                                <option value="<?php echo $role->get_id() ;?>" <?php if($role->get_id() == $this->data['role_id']){?> selected="selected" <?php }?>> <?php echo $role->get_name(); ?> </option> 
                            <?php }?>
                        </select>
                        <a href="#" class="btn btn-small btn-primary" id="filter">Filter</a>
                    </div>
                </div>
                <div class="hcms_scroll_table">
                    <table class="hcms_table adminList" width="100%">
                        <thead>
                            <tr>
                                <th><?php echo $this->translate('Image');?></th>
                                <th><a href="#" class="sort" data-column="username"><?php echo $this->translate('Username');?><b></b></a></th>
                                <th><a href="#" class="sort" data-column="first_name"><?php echo $this->translate('First Name');?><b></b></a></th>
                                <th><a href="#" class="sort" data-column="last_name"><?php echo $this->translate('Last Name');?><b></b></a></th>
                                <th><a href="#" class="sort" data-column="email"><?php echo $this->translate('Email');?><b></b></a></th>
                                <th><a href="#" class="sort" data-column="status"><?php echo $this->translate('Status');?><b></b></a></th>
                            </tr>
                        </thead>
                        <tbody id="listContainer">
                        </tbody>
                    </table>
                </div>
                <div id="pager" class="pager"></div>
            </div>
        </div>
    </div>
</div>
<script type="text/html" id="records_tpl">
<% if (rows.length > 0){
    var rowClass = 'odd';
    %>
    <% for ( var i = 0; i < rows.length; i++ ){
        rowClass = (i % 2 == 0)? 'even':'odd';
    %>
        <tr class="<%=rowClass%>">
            <td width="120">
                <% if(rows[i].image_path){ %>
                    <img src="<?php echo $this->fileWebRoot; ?><%=rows[i].image_path%>" width="50" />
                <% } %>
            </td>
            <td class="fixed-width">
                <span><%=rows[i].username%></span>
                <ul class="hcms_menu_actions">
                    <li><a href="#" class="edit" data-id="<%=rows[i].id%>"><span><?php echo $this->translate('Edit');?></span></a></li>
                    <li><a href="#" class="delete" data-id="<%=rows[i].id%>"><span><?php echo $this->translate('Delete');?></span></a></li>
                </ul>
            </td>
            <td>
                <%=rows[i].first_name%>
            </td>
            <td>
                <%=rows[i].last_name%>
            </td>
            <td>
                <%=rows[i].email%>
            </td>
            <td>
                <%=rows[i].status%>
            </td>
        </tr>
    <% } %>
<% } %>
</script>
<script type="text/javascript">
/*res-tables*/
    $(function() {
        var rt = ".res-tabs";
        // initialize NaviBar (test version)
        $(rt).restabs({
            context_obj: this,
            responsiveMode: true,
            tabPlus: true,
            resizeTimeOut: 600,
            showRemove: true
        });
        // add end tab    
        $("#listContainer").on("click", "a.edit", function(e) {
            e.preventDefault();
            var that = $(this);
            var title =  $(this).parent("li").parent("ul").parent("td").children("span").text();
            function addNewTab(){
                var ids = $(rt).restabs("addEndTab");
                setTab(ids, title);
                $(rt).restabs("activateTab", {tabId: ids.tabId});
                editDialog(that.data('id'),that.data('type_id'));  
                var tabOpenedId = "#" + ids.tabId;
                $(tabOpenedId).attr("data-pageId", that.attr("data-id"));
            }
            var numOfTabs = $(".res-tabs .tab-list li").length;
            var itIsOpen = 0;
            if (numOfTabs == 1){
                addNewTab();
            } else {
                $(".res-tabs .tab-list li").each(function(){
                    if ($(this).text() == title) {
                        itIsOpen = itIsOpen + 1;
                    }  
                });
                if (itIsOpen == 0) {
                    addNewTab();
                }
            } 
        });
        var setTab = function(ids, editTitle) {
            //console.log(editTitle);
            $(rt).restabs("setTab", ids, {
                title: editTitle,
                content: " ",
                removable: false
            });
        };
        // add new page tab
       $(".add").click(function(e){
            e.preventDefault();
            var ids = $(rt).restabs("addEndTab");
            setTab(ids, "Add new");
            $(rt).restabs("activateTab", {tabId: ids.tabId});
            editDialog(null);
            return false;
        });
    });
</script>
