<div class="introTxt">
    <h1>Box Concept</h1>
    <h2>From idea to brand strategy to final results</h2>
</div>
<p>Lorem ipsum dolor sit amet, movet putant usu in, eam iriure maiestatis ex!</p>
<div class="row innerRow">
    <div class="col-md-9 listWrapper">
        <div class="row listGroup">
            <div class="collapseContent col-md-6">
                <h3>Lorem ipsum</h3>
                <ul class="collapseContentBox">
                    <li>Lorem ipsum dolor sit amet</li>
                    <li>Movet putant</li>
                    <li>Explicari consetetur nam cu.</li>
                    <li>Consetetur nam</li>
                    <li>Movet ipsum dolor</li>
                </ul>
            </div>
            <div class="collapseContent col-md-6">
                <h3>Lorem ipsum</h3>
                <ul class="collapseContentBox">
                    <li>Lorem ipsum dolor sit amet</li>
                    <li>Movet putant</li>
                    <li>Explicari consetetur nam cu.</li>
                    <li>Consetetur nam</li>
                    <li>Movet ipsum dolor</li>
                </ul>
            </div>
        </div>
        <div class="row listGroup">
            <div class="collapseContent col-md-6">
                <h3>Lorem ipsum</h3>
                <ul class="collapseContentBox">
                    <li>Lorem ipsum dolor sit amet</li>
                    <li>Movet putant</li>
                    <li>Explicari consetetur nam cu.</li>
                    <li>Consetetur nam</li>
                    <li>Movet ipsum dolor</li>
		    <li>Movet putant</li>
                    <li>Explicari consetetur nam cu.</li>
		    <li>Movet putant</li>
                </ul>
            </div>
            <div class="collapseContent col-md-6">
                <h3>Movet putant</h3>
                <ul class="collapseContentBox">
                    <li>Lorem ipsum dolor sit amet</li>
                    <li>Movet putant</li>
                    <li>Explicari consetetur nam cu.</li>
                    <li>Consetetur nam</li>
                    <li>Movet ipsum dolor</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="row">
            <div class="col-md-12 col-xs-6 innerPageImage">
                <?php echo $this->renderPicture('design-concept-consulting-1', 'inner/design-concept-consulting/design-concept-consulting-1', 'Placeholder image for sms winning game', '.jpg');?>
            </div>
            <div class="col-md-12 col-xs-6 innerPageImage">
                <?php echo $this->renderPicture('design-concept-consulting-2', 'inner/design-concept-consulting/design-concept-consulting-2', 'Placeholder image for sms winning game', '.jpg');?>
            </div>
        </div>
    </div>
</div>
<section class="collapsibleSection">
    <h2>Description</h2>
    <div class="row description">
        <div class="col-md-9">
            <p>Lorem ipsum dolor sit amet, movet putant usu in, eam iriure maiestatis ex. Ne mea mazim tacimates, te liber sanctus mel.
		Iudico fabellas vis et. Partiendo gubergren assentior an mea, at eam quaeque alienum explicari.<br/>
		Ut vis dicant corpora, ex ferri debitis ocurreret sed, his ea sale appareat interesset.
		In suscipit liberavisse nam. An cum decore splendide, ludus timeam et sea. Ne dicat facilis eam, iusto putent evertitur te vix. 
		No sea adhuc paulo, reque disputando qui id, nec autem tempor iuvaret ea. Eos id accusam erroribus voluptaria, mediocrem explicari consetetur nam cu.
	    </p>
	    <p>Lorem ipsum dolor sit amet, movet putant usu in, eam iriure maiestatis ex. Ne mea mazim tacimates, te liber sanctus mel.
		Iudico fabellas vis et. Partiendo gubergren assentior an mea, at eam quaeque alienum explicari.<br/>
		Ut vis dicant corpora, ex ferri debitis ocurreret sed, his ea sale appareat interesset.
		In suscipit liberavisse nam. An cum decore splendide, ludus timeam et sea. Ne dicat facilis eam, iusto putent evertitur te vix. 
		No sea adhuc paulo, reque disputando qui id, nec autem tempor iuvaret ea.
	    </p>
	    <p>Lorem ipsum dolor sit amet, movet putant usu in, eam iriure maiestatis ex. Ne mea mazim tacimates, te liber sanctus mel.
		Iudico fabellas vis et. Partiendo gubergren assentior an mea, at eam quaeque alienum explicari.<br/>
		Ut vis dicant corpora, ex ferri debitis ocurreret sed, his ea sale appareat interesset.
		In suscipit liberavisse nam. An cum decore splendide, ludus timeam et sea. Ne dicat facilis eam, iusto putent evertitur te vix. 
		No sea adhuc paulo, reque disputando qui id, nec autem tempor iuvaret ea. Eos id accusam erroribus voluptaria, mediocrem explicari consetetur nam cu.
	    </p>
	    <p>Lorem ipsum dolor sit amet, movet putant usu in, eam iriure maiestatis ex. Ne mea mazim tacimates, te liber sanctus mel.
		Iudico fabellas vis et. Partiendo gubergren assentior an mea, at eam quaeque alienum explicari.<br/>
		Ut vis dicant corpora, ex ferri debitis ocurreret sed, his ea sale appareat interesset.
		In suscipit liberavisse nam. An cum decore splendide, ludus timeam et sea. Ne dicat facilis eam, iusto putent evertitur te vix. 
		No sea adhuc paulo, reque disputando qui id, nec autem tempor iuvaret ea.
	    </p>
        </div>
        <div class="col-md-3">
            <div class="row">
                <div class="col-md-12 col-xs-6 innerPageImage">
                    <?php echo $this->renderPicture('design-concept-consulting-3', 'inner/design-concept-consulting/design-concept-consulting-3', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
                <div class="col-md-12 col-xs-6 innerPageImage">
                    <?php echo $this->renderPicture('design-concept-consulting-4', 'inner/design-concept-consulting/design-concept-consulting-4', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
            </div>
        </div>  
    </div>
</section>
<section class="collapsibleSection">
    <h2>Preparations</h2>
    <div class="row">
        <div class="col-md-12">  
            <p>Lorem ipsum dolor sit amet, movet putant usu in, eam iriure maiestatis ex. Ne mea mazim tacimates, te liber sanctus mel.
		Iudico fabellas vis et. Partiendo gubergren assentior an mea, at eam quaeque alienum explicari.
		Ut vis dicant corpora, ex ferri debitis ocurreret sed, his ea sale appareat interesset.
		In suscipit liberavisse nam. An cum decore splendide, ludus timeam et sea. Ne dicat facilis eam, iusto putent evertitur te vix. 
		No sea adhuc paulo, reque disputando qui id, nec autem tempor iuvaret ea. Eos id accusam erroribus voluptaria, mediocrem explicari consetetur nam cu.
	    </p>
        </div>
    </div>
</section>