<?php
$this->slideMainDisable = true;
$this->headScript()->prependFile($this->themePath('js/download.js')); ?>

<!--<div class="row">
    <div class="col-lg-12">
        <h1>Downloads</h1>
        <h2>Get your whitepapers, logos, graphics and much more</h2>
        <p>HORISEN Marketing Technology team creates for you.</p>
    </div>
</div>-->


<div class="row">
    <div class="col-lg-12">
        <ul class="downloadLeftMenu">
            <li><a href="#item-1" class="download-items-menu active">HORISEN</a></li>
            <li><a href="#item-2" class="download-items-menu">HORISEN/horizontal</a></li>
            <li><a href="#item-3" class="download-items-menu">iCard</a></li>
            <li><a href="#item-4" class="download-items-menu">megafanapps</a></li>
            <li><a href="#item-5" class="download-items-menu">Call&amp;Pay</a></li>
            <li><a href="#item-6" class="download-items-menu">SMS&amp;Park</a></li>
        </ul>
    </div>
</div>
<div class="row">
    <div id="item-1" class="download-items active">
        <div class="col-lg-12">
            <div class="col-lg-12"><h2>HORISEN logo</h2></div>
            <div class="col-md-4">
                <h3>Full Color</h3>
                <img src="inner/downloads/downloads-content/horisen/horisen-claim-full-color.jpg"/>
                <p>All logos are available in jpg, png, eps formats and various sizes.</p>
                <a target="_self" href="/uploads/downloads/horisen/horisen-with-claim/horisen-with-claim-full-color.zip" class="btn horisenBtn downloadBtn">download</a>
            </div>
            <div class="col-md-4">
                <h3>Positive</h3>
                <img src="inner/downloads/downloads-content/horisen/horisen-claim-positive.jpg"/>
                <p>All logos are available in jpg, png, eps formats and various sizes.</p>
                <a target="_self" href="/uploads/downloads/horisen/horisen-with-claim/horisen-with-claim-positive.zip" class="btn horisenBtn downloadBtn">download</a>
            </div>
            <div class="col-md-4">
                <h3>Negative</h3>
                <img src="inner/downloads/downloads-content/horisen/horisen-claim-negative.jpg"/>
                <p>All logos are available in jpg, png, eps formats and various sizes.</p>
                <a target="_self" href="/uploads/downloads/horisen/horisen-with-claim/horisen-with-claim-negative.zip" class="btn horisenBtn downloadBtn">download</a>
            </div>
        </div>
        <div class="col-lg-12">
            <div class="col-lg-12"><h2>HORISEN logo without claim</h2></div>
            <div class="col-md-4">
                <h3>Full Color</h3>
                <img src="inner/downloads/downloads-content/horisen/horisen-full-color.jpg"/>
                <p>All logos are available in jpg, png, eps formats and various sizes.</p>
                <a target="_self" href="/uploads/downloads/horisen/horisen-without-claim/horisen-without-claim-full-color.zip" class="btn horisenBtn downloadBtn">download</a>
            </div>
            <div class="col-md-4">
                <h3>Positive</h3>
                <img src="inner/downloads/downloads-content/horisen/horisen-positive.jpg"/>
                <p>All logos are available in jpg, png, eps formats and various sizes.</p>
                <a target="_self" href="/uploads/downloads/horisen/horisen-without-claim/horisen-without-claim-positive.zip" class="btn horisenBtn downloadBtn">download</a>
            </div>
            <div class="col-md-4">
                <h3>Negative</h3>
                <img src="inner/downloads/downloads-content/horisen/horisen-negative.jpg"/>
                <p>All logos are available in jpg, png, eps formats and various sizes.</p>
                <a target="_self" href="/uploads/downloads/horisen/horisen-without-claim/horisen-without-claim-negative.zip" class="btn horisenBtn downloadBtn">download</a>
            </div>
        </div>
    </div>
    <div id="item-2" class="download-items">
        <div class="col-lg-12">
            <div class="col-lg-12"><h2>HORISEN horizontal logo</h2></div>
            <div class="col-md-4">
                <h3>Full Color</h3>
                <img src="inner/downloads/downloads-content/horisen-horizontal/horisen-horizontal-full-color.jpg"/>
                <p>All logos are available in jpg, png, eps formats and various sizes.</p>
                <a target="_self" href="/uploads/downloads/horisen-horizontal/horisen-horizontal-full-color.zip" class="btn horisenBtn downloadBtn">download</a>
            </div>
            <div class="col-md-4">
                <h3>Positive</h3>
                <img src="inner/downloads/downloads-content/horisen-horizontal/horisen-horizontal-positive.jpg"/>
                <p>All logos are available in jpg, png, eps formats and various sizes.</p>
                <a target="_self" href="/uploads/downloads/horisen-horizontal/horisen-horizontal-positive.zip" class="btn horisenBtn downloadBtn">download</a>
            </div>
            <div class="col-md-4">
                <h3>Negative</h3>
                <img src="inner/downloads/downloads-content/horisen-horizontal/horisen-horizontal-negative.jpg"/>
                <p>All logos are available in jpg, png, eps formats and various sizes.</p>
                <a target="_self" href="/uploads/downloads/horisen-horizontal/horisen-horizontal-negative.zip" class="btn horisenBtn downloadBtn">download</a>
            </div>
        </div>
    </div>
    <div id="item-3" class="download-items">
        <div class="col-lg-12">
            <div class="col-lg-12"><h2>iCard logo</h2></div>
            <div class="col-md-4">
                <h3>Full Color</h3>
                <img src="inner/downloads/downloads-content/icard/icard-full-color.jpg"/>
                <p>All logos are available in jpg, png, eps formats and various sizes.</p>
                <a target="_self" href="/uploads/downloads/icard/icard-full-color.zip" class="btn horisenBtn downloadBtn">download</a>
            </div>
            <div class="col-md-4">
                <h3>Positive</h3>
                <img src="inner/downloads/downloads-content/icard/icard-positive.jpg"/>
                <p>All logos are available in jpg, png, eps formats and various sizes.</p>
                <a target="_self" href="/uploads/downloads/icard/icard-positive.zip" class="btn horisenBtn downloadBtn">download</a>
            </div>
            <div class="col-md-4">
                <h3>Negative</h3>
                <img src="inner/downloads/downloads-content/icard/icard-negative.jpg"/>
                <p>All logos are available in jpg, png, eps formats and various sizes.</p>
                <a target="_self" href="/uploads/downloads/icard/icard-negative.zip" class="btn horisenBtn downloadBtn">download</a>
            </div>
        </div>
    </div>
    <div id="item-4" class="download-items">
        <div class="col-lg-12">
            <div class="col-lg-12"><h2>megafanapps logo</h2></div>
            <div class="col-md-4">
                <h3>Full Color</h3>
                <img src="inner/downloads/downloads-content/megafanapps/megafanapps-full-color.jpg"/>
                <p>All logos are available in jpg, png, eps formats and various sizes.</p>
                <a target="_self" href="/uploads/downloads/megafanapps/megafanapps-full-color.zip" class="btn horisenBtn downloadBtn">download</a>
            </div>
            <div class="col-md-4">
                <h3>Positive</h3>
                <img src="inner/downloads/downloads-content/megafanapps/megafanapps-positive.jpg"/>
                <p>All logos are available in jpg, png, eps formats and various sizes.</p>
                <a target="_self" href="/uploads/downloads/megafanapps/megafanapps-positive.zip" class="btn horisenBtn downloadBtn">download</a>
            </div>
            <div class="col-md-4">
                <h3>Negative</h3>
                <img src="inner/downloads/downloads-content/megafanapps/megafanapps-negative.jpg"/>
                <p>All logos are available in jpg, png, eps formats and various sizes.</p>
                <a target="_self" href="/uploads/downloads/megafanapps/megafanapps-negative.zip" class="btn horisenBtn downloadBtn">download</a>
            </div>
        </div>
    </div>
    <div id="item-5" class="download-items">
        <div class="col-lg-12">
            <div class="col-lg-12"><h2>Call&amp;Pay logo</h2></div>
            <div class="col-md-4">
                <h3>Full Color</h3>
                <img src="inner/downloads/downloads-content/call-pay/call-pay-full-color.jpg"/>
                <p>All logos are available in jpg, png, eps formats and various sizes.</p>
                <a target="_self" href="/uploads/downloads/call-pay/call-pay-full-color.zip" class="btn horisenBtn downloadBtn">download</a>
            </div>
            <div class="col-md-4">
                <h3>Positive</h3>
                <img src="inner/downloads/downloads-content/call-pay/call-pay-positive.jpg"/>
                <p>All logos are available in jpg, png, eps formats and various sizes.</p>
                <a target="_self" href="/uploads/downloads/call-pay/call-pay-positive.zip" class="btn horisenBtn downloadBtn">download</a>
            </div>
            <div class="col-md-4">
                <h3>Negative</h3>
                <img src="inner/downloads/downloads-content/call-pay/call-pay-negative.jpg"/>
                <p>All logos are available in jpg, png, eps formats and various sizes.</p>
                <a target="_self" href="/uploads/downloads/call-pay/call-pay-negative.zip" class="btn horisenBtn downloadBtn">download</a>
            </div>
        </div>
    </div>
    <div id="item-6" class="download-items">
        <div class="col-lg-12">
            <div class="col-lg-12"><h2>SMS&amp;Park logo</h2></div>
            <div class="col-md-4">
                <h3>Full Color</h3>
                <img src="inner/downloads/downloads-content/sms-park/sms-park-full-color.jpg"/>
                <p>All logos are available in jpg, png, eps formats and various sizes.</p>
                <a target="_self" href="/uploads/downloads/sms-park/sms-park-full-color.zip" class="btn horisenBtn downloadBtn">download</a>
            </div>
            <div class="col-md-4">
                <h3>Positive</h3>
                <img src="inner/downloads/downloads-content/sms-park/sms-park-positive.jpg"/>
                <p>All logos are available in jpg, png, eps formats and various sizes.</p>
                <a target="_self" href="/uploads/downloads/sms-park/sms-park-positive.zip" class="btn horisenBtn downloadBtn">download</a>
            </div>
            <div class="col-md-4">
                <h3>Negative</h3>
                <img src="inner/downloads/downloads-content/sms-park/sms-park-negative.jpg"/>
                <p>All logos are available in jpg, png, eps formats and various sizes.</p>
                <a target="_self" href="/uploads/downloads/sms-park/sms-park-negative.zip" class="btn horisenBtn downloadBtn">download</a>
            </div>
        </div>
    </div>
</div>



















