<?php
//we don't need layout - the page will contain all needed
$this->layout()->setLayout('intro');
?>


<div style="text-align:center; padding-top:200px;">

<h2>This is an intro page</h2>

<p>Five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.<br /> It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publish.</p>
</div>