<div class="introTxt">
    <h1>Landing Pages</h1>
    <h2>Fast converters which carry effective content</h2>
</div>
<p>Call-to-action tools that capture early customers fast!</p>
<div class="row innerRow">
    <div class="col-md-9 listWrapper">
        <div class="row listGroup">
            <div class="collapseContent col-md-6">
                <h3>You want</h3>
                <ul class="collapseContentBox">
                    <li>Effective new promotion web page</li>
                    <li>Time-limited promo campaigns</li>
                    <li>Better product &quot;shopping window&quot;</li>
                    <li>Attractive design for your selling page</li>
                    <li>Short time to market your promo page</li>
                </ul>
            </div>
            <div class="collapseContent col-md-6">
                <h3>We have</h3>
                <ul class="collapseContentBox">
                    <li>Customizable web page elements</li>
                    <li>Flexible and fast promo page development</li>
                    <li>Automation process that establishes communication with customers</li>
                    <li>Many custom design options at hand</li>
                    <li>Fast implementation of your landing page</li>
                </ul>
            </div>
        </div>
        <div class="row listGroup">
            <div class="collapseContent col-md-6">
                <h3>Features</h3>
                <ul class="collapseContentBox">
                    <li>Free text-editable fields</li>
                    <li>Drag and drop elements</li>
                    <li>Automated e-mail notifications</li>
                    <li>Custom call-to-actions</li>
                    <li>A/B testing included or on demand</li>
                    <li>Conversion analysis report</li>
                    <li>Contact database and quality data export</li>
                    <li>Custom design and CSS customization</li>
                </ul>
            </div>
            <div class="collapseContent col-md-6">
                <h3>Purpose</h3>
                <ul class="collapseContentBox">
                    <li>Fast conversions</li>
                    <li>Capturing quality contacts</li>
                    <li>Instant selling</li>
                    <li>Early-bird product promotion</li>
                    <li>Service quality evaluation</li>
                    <li>Separate product's shopping window</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="row">
            <div class="col-md-12 col-xs-6 innerPageImage">
                <?php echo $this->renderPicture('landing-page-1', 'inner/landing-page/landing-page-1', 'Landing pages are product shopping windows', '.jpg');?>
            </div>
            <div class="col-md-12 col-xs-6 innerPageImage">
                <?php echo $this->renderPicture('landing-page-2', 'inner/landing-page/landing-page-2', 'New promo pages made thanks to landing pages', '.jpg');?>
            </div>
        </div>
    </div>
</div>
<section class="collapsibleSection">
    <h2>Description</h2>
    <div class="row description">
        <div class="col-md-9">
            <p>The purpose of an effective landing pages is to convert visitors into leads. But how? An attractive landing page with great design 
                and a custom contact form is simply not enough. Landing pages need to speak to visitors immediately and be built with a deep 
                understanding of their needs and expectations. That’s why this unique page must perform this magic for your business in a few 
                seconds.</p> 

            <p>Landing pages are very flexible when it comes to page editing and form creation. With smart content distribution, you can generate 
                and convert a lot of traffic that would otherwise have come to one page only. Organize a special promotion or a time-limited campaign 
                for your new product / service.  Connect your customers directly with these promotions and accelerate the conversion process. Landing 
                pages are made to attract users’ attention and thus are one of the most critical componenta of your web site.</p>

            <p>Another thing which can be included prior to real landing page launching is A/B testing. In this way, you will be sure which type of 
                content, page composition and design works best! With customizable call-to-actions you can easily attract the right visitors to come 
                and see your proposal or sales pitch. You are able to test any element including headlines, call-to-action and images; also preview 
                differently edited landing pages and see which version drives the most conversions.</p>

            <p>With its specific URL or sub-domain, a landing page can be easily analysed. Each promotion can be measured continuously in order to 
                make future promotion optimizations or adaptations (if needed).</p> 

            <p>The automated email notifications are a great point for successful email marketing and regular newsletter updates. In this way you 
                not only establish communication with your customers, but also remind them of other offers and keep them aware of your brand.</p>

        </div>
        <div class="col-md-3">
            <div class="row">
                <div class="col-md-12 col-xs-6 innerPageImage">
                    <?php echo $this->renderPicture('landing-page-3', 'inner/landing-page/landing-page-3', 'Landing pages allow fully custom design', '.jpg');?>
                </div>
                <div class="col-md-12 col-xs-6 innerPageImage">
                    <?php echo $this->renderPicture('landing-page-4', 'inner/landing-page/landing-page-4', 'Instant selling happens with landing pages', '.jpg');?>
                </div>
            </div>
        </div>  
    </div>
</section>
<section class="collapsibleSection">
    <h2>Preparations</h2>
    <div class="row">
        <div class="col-md-12">  
            <h3>Preparations on your side</h3>
            <ol>
                <li>Idea for promotion (e.g. seasonal promotion, sales, call-to-action for joining a cause, etc.)</li>
                <li>Writing text elements with call-to-action included </li>
                <li>Choosing fields for contact form or e-mail subscription </li>
                <li>Decide upon design elements and visual appearance</li>
                <li>Do the testing and see which version suits you best</li>
                <li>Launch your landing page and promote it on different offline/online media, including social media channels as well</li>
            </ol>
            <h3>How your customers end up on your landing page</h3>
            <ol>
                <li>You created an advertisement </li>
                <li>The Ad is posted on: your promo flyers, store banner, TV Ad, product package, or social media accounts including Facebook or Google Ads</li>
                <li>By entering your website page URL or clicking on the promo link (online Ad), visitors are redirected to landing page first</li>
                <li>They see the attractive content and leave their data / answer the question or whatever you defined within a promotion</li>
                <li>After receiving an email notification, they can proceed to another activity; otherwise, this will be the last step – if prizes 
                    or discounts are, for example, announced to be distributed later</li>
            </ol>
        </div>
    </div>
</section>