<div class="introTxt">
    <h1>Design Portfolio</h1>
    <h2>We implement without limits</h2>
</div>
<p>It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
<p>It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
<h2>Our areas</h2>
<section class="collapsibleSection designSection">
    <h3>Creative consulting, analysis and optimization</h3>
    <div class="row description">
        <div class="col-md-12 listWrapper">
            <div class="row listGroup">
                <div class="collapseContent col-md-7">
                    <?php echo $this->renderPicture('consultation', 'inner/designs/designs1', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
                <div class="collapseContent col-md-5">
                    <p>Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions.</p>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="collapsibleSection designSection">
    <h3>Logo Design</h3>
    <div class="row description">
        <div class="col-md-12 listWrapper">
            <div class="row listGroup">
                <div class="collapseContent col-md-7">
                    <?php echo $this->renderPicture('logo-design', 'inner/designs/designs2', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
                <div class="collapseContent col-md-5">
                    <p>Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions.</p>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="collapsibleSection designSection">
    <h3>Corporate Design</h3>
    <div class="row description">
        <div class="col-md-12 listWrapper">
            <div class="row listGroup">
                <div class="collapseContent col-md-7">
                    <?php echo $this->renderPicture('corporate-design', 'inner/designs/designs3', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
                <div class="collapseContent col-md-5">
                    <p>Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions.</p>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="collapsibleSection designSection">
    <h3>Illustrations and Image Processing</h3>
    <div class="row description">
        <div class="col-md-12 listWrapper">
            <div class="row listGroup">
                <div class="collapseContent col-md-7">
                    <?php echo $this->renderPicture('image-editing', 'inner/designs/designs4', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
                <div class="collapseContent col-md-5">
                    <p>Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions.</p>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="collapsibleSection designSection">
    <h3>Flyer and Advertisements Design</h3>
    <div class="row description">
        <div class="col-md-12 listWrapper">
            <div class="row listGroup">
                <div class="collapseContent col-md-7">
                    <?php echo $this->renderPicture('flyer', 'inner/designs/designs5', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
                <div class="collapseContent col-md-5">
                    <p>Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions.</p>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="collapsibleSection designSection">
    <h3>Editorial Design – Brochures, Magazines and Books</h3>
    <div class="row description">
        <div class="col-md-12 listWrapper">
            <div class="row listGroup">
                <div class="collapseContent col-md-7">
                    <?php echo $this->renderPicture('editorial-design', 'inner/designs/designs6', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
                <div class="collapseContent col-md-5">
                    <p>Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions more recently with desktop publishing software.</p>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="collapsibleSection designSection">
    <h3>Sales Collateral</h3>
    <div class="row description">
        <div class="col-md-12 listWrapper">
            <div class="row listGroup">
                <div class="collapseContent col-md-7">
                    <?php echo $this->renderPicture('sales-collateral', 'inner/designs/designs7', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
                <div class="collapseContent col-md-5">
                    <p>Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions more recently with desktop publishing software.</p>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="collapsibleSection designSection">
    <h3>Packaging Design</h3>
    <div class="row description">
        <div class="col-md-12 listWrapper">
            <div class="row listGroup">
                <div class="collapseContent col-md-7">
                    <?php echo $this->renderPicture('packaging', 'inner/designs/designs8', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
                <div class="collapseContent col-md-5">
                    <p>Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions more recently with desktop publishing software.</p>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="collapsibleSection designSection">
    <h3>(Responsive) Web Design</h3>
    <div class="row description">
        <div class="col-md-12 listWrapper">
            <div class="row listGroup">
                <div class="collapseContent col-md-7">
                    <?php echo $this->renderPicture('web-design', 'inner/designs/designs9', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
                <div class="collapseContent col-md-5">
                    <p>Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions more recently with desktop publishing software.</p>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="collapsibleSection designSection">
    <h3>Social Media Marketing Campaigns</h3>
    <div class="row description">
        <div class="col-md-12 listWrapper">
            <div class="row listGroup">
                <div class="collapseContent col-md-7">
                    <?php echo $this->renderPicture('social-media', 'inner/designs/designs10', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
                <div class="collapseContent col-md-5">
                    <p>Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions more recently with desktop publishing software.</p>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="collapsibleSection designSection">
    <h3>Video tutorials / Company Presentations</h3>
    <div class="row description">
        <div class="col-md-12 listWrapper">
            <div class="row listGroup">
                <div class="collapseContent col-md-7">
                    <?php echo $this->renderPicture('video-tutorial', 'inner/designs/designs11', 'Placeholder image for sms winning game', '.jpg');?>
                </div>
                <div class="collapseContent col-md-5">
                    <p>Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions more recently with desktop publishing software.</p>
                </div>
            </div>
        </div>
    </div>
</section>