<div class="introTxt">
    <h1>Tile Concept</h1>
    <h2>Display content through tiles concept</h2>
</div>
<p>Lorem ipsum dolor sit amet, movet putant usu in, eam iriure maiestatis ex!</p>
<p>Lorem ipsum dolor sit amet, movet putant usu in, eam iriure maiestatis ex!</p>
<div class="row servicesRow">
    <h3>Lorem ipsum</h3>
    <div class="col-md-6">
	<ul class="collapseContentBox">
	    <li>Lorem ipsum dolor sit amet</li>
	    <li>Movet putant</li>
	    <li>Explicari consetetur nam cu.</li>
	    <li>Consetetur nam</li>
	    <li>Movet ipsum dolor</li>
	</ul>
    </div>
    <div class="col-md-6">
        <ul class="collapseContentBox">
	    <li>Lorem ipsum dolor sit amet</li>
	    <li>Movet putant</li>
	    <li>Explicari consetetur nam cu.</li>
	    <li>Consetetur nam</li>
	    <li>Movet ipsum dolor</li>
	</ul>
    </div>
</div>
<div class="graphicOverview">
    <div class="row">
        <div class="col-md-4 designInnerPageImage">
            <?php echo $this->renderPicture('logo-design', 'inner/services/logo-design', 'Placeholder image for our services', '.jpg');?>
            <p>Logo design</p>
        </div>
        <div class="col-md-4 designInnerPageImage">
            <?php echo $this->renderPicture('corporate-design', 'inner/services/corporate-design', 'Placeholder image for our services', '.jpg');?>
            <p>Corporate design</p>
        </div>
        <div class="col-md-4 designInnerPageImage">
            <?php echo $this->renderPicture('illustration', 'inner/services/illustration', 'Placeholder image for our services', '.jpg');?>
            <p>Illustration</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4 designInnerPageImage">
            <?php echo $this->renderPicture('flyer', 'inner/services/flyer', 'Placeholder image for our services', '.jpg');?>
            <p>Flyer</p>
        </div>
        <div class="col-md-4 designInnerPageImage">
            <?php echo $this->renderPicture('magazin-design', 'inner/services/magazin-design', 'Placeholder image for our services', '.jpg');?>
            <p>Magazine design</p>
        </div>
        <div class="col-md-4 designInnerPageImage">
            <?php echo $this->renderPicture('sales-promotion', 'inner/services/sales-promotion', 'Placeholder image for our services', '.jpg');?>
            <p>Sales Collateral</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4 designInnerPageImage">
            <?php echo $this->renderPicture('package-design', 'inner/services/package-design', 'Placeholder image for our services', '.jpg');?>
            <p>Package design</p>
        </div>
        <div class="col-md-4 designInnerPageImage">
            <?php echo $this->renderPicture('multimedia-campaigns', 'inner/services/multimedia-campaigns', 'Placeholder image for our services', '.jpg');?>
            <p>Multimedia campaigns</p>
        </div>
        <div class="col-md-4 designInnerPageImage">
            <?php echo $this->renderPicture('video-tutorials', 'inner/services/video-tutorials', 'Placeholder image for our services', '.jpg');?>
            <p>Video tutorials</p>
        </div>
    </div>
</div>
