<div class="introTxt">
    <h1>Videos</h1>
    <h2>Shape your business into emotional storytelling</h2>
</div>
<p>Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions more recently with desktop publishing software.</p>
		    <p>Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like including versions more recently with desktop publishing software.</p>
<div class="row servicesRow">
    <h3>Video Design</h3>
    <div class="col-md-6">
        <ul>
            <li>Product / service videos</li>
            <li>Animations</li>
            <li>Corporate videos</li>
            <li>Showcase / testimonial videos</li>
        </ul>
    </div>
    <div class="col-md-6">
        <ul>
            <li>Sales videos</li>
            <li>Tutorial videos</li>
            <li>Event videos</li>
            <li>Presentation videos</li>
        </ul>
    </div>
</div>
<div class="graphicOverview">
    <div class="row">
        <div class="col-md-4 videoInnerPageImage">
            <?php echo $this->renderPicture('product', 'inner/videos/product', 'Placeholder image for videos', '.jpg');?>
            <p>Product/service videos</p>
        </div>
        <div class="col-md-4 videoInnerPageImage">
            <?php echo $this->renderPicture('animations', 'inner/videos/animations', 'Placeholder image for videos', '.jpg');?>
            <p>Animations</p>
        </div>
        <div class="col-md-4 videoInnerPageImage">
            <?php echo $this->renderPicture('corporate-videos', 'inner/videos/corporate-videos', 'Placeholder image for videos', '.jpg');?>
            <p>Corporate videos</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4 videoInnerPageImage">
            <?php echo $this->renderPicture('showcase', 'inner/videos/showcase', 'Placeholder image for videos', '.jpg');?>
            <p>Showcase/testimonial videos</p>
        </div>
        <div class="col-md-4 videoInnerPageImage">
            <?php echo $this->renderPicture('sales-videos', 'inner/videos/sales-videos', 'Placeholder image for videos', '.jpg');?>
            <p>Sales videos</p>
        </div>
        <div class="col-md-4 videoInnerPageImage">
            <?php echo $this->renderPicture('tutorial-videos', 'inner/videos/tutorial-videos', 'Placeholder image for videos', '.jpg');?>
            <p>Tutorial videos</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4 videoInnerPageImage">
            <?php echo $this->renderPicture('event-videos', 'inner/videos/event-videos', 'Placeholder image for videos', '.jpg');?>
            <p>Event videos</p>
        </div>
        <div class="col-md-4 videoInnerPageImage">
            <?php echo $this->renderPicture('presentation-videos', 'inner/videos/presentation-videos', 'Placeholder image for videos', '.jpg');?>
            <p>Presentation videos</p>
        </div>
    </div>
</div>
