<script>
$(function(){
    $("a.fBox_prev").fancybox({
        'transitionIn'	:	'fade',
        'transitionOut'	:	'fade',
        'speedIn'		:	600, 
        'speedOut'		:	200, 
        'overlayShow'	:	false
    });
  
});
</script>
<div class="pageContentHolder eleven columns">
<h1 class="inner"><?php echo $this->escape($this->page->get_title());?></h1>
<p><?php echo HCMS_Utils_Time::timeMySql2Custom($this->page->get_extension()->get_start_date(), "EEEE, d. MMM yyyy" );?></p>
<article class="single-tourdate clearfix">
	<table>
      <tr>
          <td style="padding-right: 25px;">
        	<?php if ($this->page->get_data('image') != ''){ ?>
    <?php if($this->page->get_data('image_preview') != '') { ?>
            <a class="fBox_prev" rel="fBox_prev" title="<?php echo $this->page->get_title(); ?>" href="/content/1/<?php echo $this->page->get_data('image_preview'); ?>"> 
                <img src="<?php echo $this->escape($this->page->get_data('image'));?>" /> 
            </a>
    <?php }else{ ?>
                <img src="<?php echo $this->escape($this->page->get_data('image'));?>" /> 
    <?php } ?>
        </td>
        <td>
        	<?php } ?>
            <div>
                <p><?php echo $this->translate("Showtime")?>: <?php echo $this->escape($this->page->get_extension()->get_start_time()) . " - " . $this->escape($this->page->get_extension()->get_end_time()); ?></p>
                <p><?php echo $this->page->get_content();?></p>
            </div>
        </td>
      </tr>
    </table>
</article>

<a class="more" href="<?php echo $this->url(array('module'=>'tourdate','controller'=>'page','action'=>'list', 'timeline' => $this->timeline), 'cms', true);?>">&laquo; <?php echo $this->translate('back');?></a>
</div>
<div class="rightSideContent six columns ">
    <div class="socialSideContainer">
        <nav class="socialSide">
            <a href="#" class="facebook"></a>
            <a href="#" class="twitter"></a>
            <a href="#" class="google"></a>
            <a href="#" class="soc1"></a>
            <a href="#" class="linkedIn"></a>
            <a href="#" class="soc2"></a>
            <a href="#" class="soc3"></a>
        </nav> 
    </div>
</div>