<div class="pageContentHolder eleven columns">
<?php
    $this->headLink()->appendStylesheet( '/modules/tourdate/css/style.css');

    if(count($this->pages) > 0){
?>
<h1><?php echo $this->translate("Tourdates"); ?></h1>
<p>
 <?php echo $this->translate("Tourdate intro text"); ?>
</p>
<hr />
<table class="tourdates">
    <tr>
        <th width="80"><?php echo $this->translate("Image")?>:</th>
        <th width="120"><?php echo $this->translate("Datum")?>:</th>
        <th width="180"><?php echo $this->translate("Tourdate");?>:</th>
        <th width="120"><?php echo $this->translate("Showtime")?>:</th>
        <th width="100"></th>
    </tr>
<?php
/* @var $page Cms_Model_Page */
foreach ($this->pages as $page) {
?>
    <tr>
        <td class="img_holder"><a href="<?php echo $this->url(array('module'=>'tourdate','controller'=>'page','action'=>'index','url_id'=>$page->get_url_id()),$this->route,true);?>"><img src="<?php echo $this->escape($page->get_data('image_list'));?>" /></a></td>
        <td><?php echo HCMS_Utils_Time::timeMySql2Custom($page->get_extension()->get_start_date(), "EEEE, d. MMM yyyy" );?></td>
        <td>
            <div>
            <img class="countries" src="../../images/countries/<?php echo strtolower(substr($page->get_data('country'),0,1)."/").$this->escape($page->get_data('country')).".png";?>" style="width:18px; vertical-align: top;" />
            <h5><?php echo $this->escape($page->get_title());?></h5>
            </div>
            <p>
                <?php echo $this->escape($page->get_data('subtitle'));?>
            </p>
        </td>
        <td>
                <?php echo $this->escape($page->get_extension()->get_start_time()) . " - " . $this->escape($page->get_extension()->get_end_time()); ?>
        </td>
        <td>
            <?php 
            $content = $page->get_content();
            if($content != ''){
            ?>
            <a href="<?php echo $this->url(array('module'=>'tourdate','controller'=>'page','action'=>'index','url_id'=>$page->get_url_id()),$this->route,true);?>"><?php echo $this->translate('read more');?></a>
        <?php } ?>
        </td>
    </tr>
    

<?php
}
?>
</table>
<?php
    $this->addScriptPath(APPLICATION_PATH . '/modules/cms/views/scripts/');
    echo $this->paginationControl($this->paginator,'Sliding','paginator.phtml',array('route'=>$this->route,'listingParams'=>$this->listingParams));
}
else{
    echo "<p>" . $this->translate('No Tourdates are found') . "</p>";
}
?>

</div>
<div class="rightSideContent six columns ">
    <div class="socialSideContainer">
        <nav class="socialSide">
            <a href="#" class="facebook"></a>
            <a href="#" class="twitter"></a>
            <a href="#" class="google"></a>
            <a href="#" class="soc1"></a>
            <a href="#" class="linkedIn"></a>
            <a href="#" class="soc2"></a>
            <a href="#" class="soc3"></a>
        </nav> 
    </div>
</div>