<?php
     $this->headScript()->appendFile("/js/modernizr.js");
     $this->headScript()->appendFile("/modules/music/js/niftyplayer.js");
     $this->headLink()->appendStylesheet("/modules/music/css/style.css");
     $this->headScript()->appendFile("/modules/music/js/music.js");
?>

<div class="hidden">
	<audio id="audio" controls preload="auto" autobuffer autoplay="autoplay" onended="audioNext();"></audio>
	<div id="swfMp3Player">
		<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,0,0" width="165" height="37" id="niftyPlayer1" align="">
		 <param name=movie value="/modules/music/flash/niftyplayer.swf?as=0">
		 <param name=quality value=high>
		 <param name=bgcolor value=#FFFFFF>
		 <embed src="/modules/music/flash/niftyplayer.swf?as=0" quality=high bgcolor=#FFFFFF width="165" height="37" name="niftyPlayer1" align="" type="application/x-shockwave-flash" swLiveConnect="true" pluginspage="http://www.macromedia.com/go/getflashplayer">
		</embed>
		</object>
	</div>
</div>

<?php 
if($this->albums){
    foreach($this->albums as $ak => $album){ 
?>

<div class="musicItem">
    <div class="coverHolder">
        <img src="<?php echo $album->get_photo(); ?>" alt="" />
    </div>
    <div class="playerHolder">
        <div class="playerButtons">
            <?php if($this->jSong[$album->get_id()] != "[]"){ ?>
            <input type="hidden" class="audioFile" name="audioFile[]" value='{"song":<?php
                   //{"song":[{"title":"Set Fire To The Rain","mp3":"\/content\/mp3\/Set Fire To The Rain.mp3"},{"title":"Sal","mp3":"\/content\/mp3\/Sal.mp3"},{"title":"Sejn","mp3":"\/content\/mp3\/Sejn.mp3"},{"title":"Tonight","mp3":"\/content\/mp3\/Tonight.mp3"}
                   echo $this->jSong[$album->get_id()];
                   ?>}' />
            <input type="hidden" class="currentAudio" name="currentAudio[]" value='0' />
            <div class="playerTitle"></div>
            <div class="playerAction prev"></div>
            <div class="playerAction pause"></div>
            <div class="playerAction play"></div>
            <div class="playerAction next"></div>
            <?php } ?>
        </div>
    </div>
    <div class="musicDescriptionHolder">
        <p><?php echo $album->get_description(); ?></p>
        <a href="mailto:joe@horisen.com?subject=Bestellen per E-mail <?php echo $album->get_title(); ?>" class="link">» Bestellen per E-mail</a>
    </div>
    <div class="clear"></div>
</div>

<?php 
    }
}
?>

<div id="pager">
<?php
$this->addScriptPath(APPLICATION_PATH . '/modules/cms/views/scripts/');
echo $this->paginationControl($this->paginator,'Sliding','paginator.phtml',array('route'=>$this->route,'listingParams'=>$this->listingParams));
?>
</div>