<?php
$this->slideMainDisable = true;
if($this->page->get_code() == 'api-manuals'){
    $removeApiToc = true;
}
else{    
    $removeApiToc = false;
}

$this->headScript()->appendFile('/plugins/bootstrap/js/bootstrap.min.js');
if(!$removeApiToc){
    $this->headScript()->appendFile($this->themePath('js/api.js?v=2014-11-18'));
}
$this->headLink()->appendStylesheet($this->themePath('css/api.css?v=2014-11-18'));

$this->headLink()->appendStylesheet($this->themePath('plugins/prettify/prettify.css'));
$this->headScript()->appendFile($this->themePath('plugins/prettify/prettify.js'));
?>
<div id="apiMenu" class="col-md-12">
    <?php echo $this->navigation()->menu()->setUseTranslator(false)->renderMenu($this->menuItems['footer'],array('ulClass' => 'api-menu', 'indent' => 20, 'onlyActiveBranch' => true, 'renderParents' => false, 'minDepth' => 2,'maxDepth' => 3)); ?>
</div>
<?php if(!$removeApiToc){ ?>
<div class="col-md-3 bs-docs-sidebar">
    <div id="apiToc"></div> 
</div>
<?php } ?>
<div id="apiContent" class="col-md-9">
    <?php echo $this->renderPage($this->page); ?>    
</div>
