<?php $classes = isset($this->field['css_class'])? $this->field['css_class']: 'form-group col-sm-6 col-xs-12'; ?>
    <div id="field-<?php echo $this->fieldId; ?>" class="<?php echo $classes;?>">
        <input type="hidden" name="data[<?php echo $this->fieldId; ?>]" value="no" />

        <label for="data[<?php echo $this->fieldId; ?>]"><?php echo $this->translate($this->field['name']);?> <?php if(isset($this->field['required']) && $this->field['required']){echo '*';}?></label>
        <input type="checkbox" name="data[<?php echo $this->fieldId; ?>]" id="data[<?php echo $this->fieldId; ?>]" value="yes" <?php echo $this->formSelected($this->data, $this->fieldId, 'yes','checked');  ?> />
        
        <span class="required <?php echo $this->errorMessages($this->errors, 'error', $this->fieldId, true);?>"><?php echo $this->errorMessages($this->errors, 'error', $this->fieldId);?></span>
    </div>