<h1>HTTP MNP Protocol</h1>

<h2>Document overview</h2>

<h3>Scope</h3>
<p>Scope of this document is to provide specification of HTTP MNP Query Service.</p>

<h3>Target audience</h3>

<p>This is internal HORISEN document to serve as technical guidelines for implementing HTTP MNP Query Service. When service becomes production stable target audience will be Customers.</p>

<h2>Service overview</h2>

<p>Horisen MNP Service helps customers to discover MNP (Mobile Number Portability) information about given MSISDN. MNP information is about which mobile operator (identified by MCC/MNC) is handling given subscriber MSISDN. There may be MSISDNs that are not active but still belonging to some mobile operator.</p>

<h2>Customer Account creation</h2>

<p>In order to have service enabled, Horisen will create following data for customer:</p>

<ol>
    <li>Customer ID</li>
    <li>Username for MNP Query account</li>
    <li>Password for MNP Query account</li>
</ol>

<p>Customer needs to provide following data:</p>

<ol>
    <li>Set of IP addresses from which queries will be sent</li>
</ol>

<h3>Querying MNP/HLR information</h3>

<p>MNP/HLR information can be queried using synchronous method. Query result is returned back in content of HTTP response.</p>

<h3>Sending MNP query</h3>

<p>Querys need to be sent using HTTP/HTTPS 1.0 protocol to URL:</p>

<pre class="prettyprint">http://sms.horisen.info:12015/mnp</pre>

<p>Query parameters can be sent as GET.</p>

<p>Customer sends query with following parameters:</p>

<div class="table-responsive">
    <table class="table table-hover table-bordered api-table">
        <tr>
            <th>Name</th>
            <th>Default value</th>
            <th>Description</th>
            <th>Example</th>
        </tr>
        <tr>
            <td>msisdn</td>
            <td>-</td>
            <td>MSISDN ininternational formatwith or without leading'+'</td>
            <td>+41787078880</td>
        </tr>
        <tr>
            <td>user</td>
            <td>-</td>
            <td>Account username</td>
            <td>testuser</td>
        </tr>
        <tr>
            <td>password</td>
            <td>-</td>
            <td>Account password</td>
            <td>testpass</td>
        </tr>
    </table>
</div>

<p>If query is accepted server will return in HTTP response:</p>

<ol>
    <li>HTTP Status code 2xx</li>
    <li>Content:</li>
</ol>

<p>IMM QID:135c5eea40008a01807c7229938dd852 MCC:228 MNC:03 ERRCODE:000 ERRDESC:</p>

<p>Field ERRCODE may be RC_OK(000) or RC_UNRELIABLE(151). Response RC_OK is returned in
case that response is provided in reliable way. RC_ UNRELIABLE is returned when response coudn't
be provided in reliable way (MNP data source is not working) but MCC/MNC pair is discovered by
checking Mobile Operator prefix database.</p>

<p>If query coudn't be processed:</p>

<ol>
    <li>HTTP Status code 4xx or 5xx</li>
    <li>If possible, content: ERR &lt;error code&gt; &lt;error message&gt;</li>
</ol>

<p>Example:</p>
<code>ERR 113 No credit on account balance</code>

<h3>Submission examples</h3>

<pre class="prettyprint">
    https://sms.horisen.info:12015/mnp?msisdn=41787078880&user=testuser&password=testpass
</pre>

<p>As shown in example, all HTTP parameters need to be URL encoded.</p>

<p>This example sends MNP Query for:</p>

<ul>
    <li>account testuser with its password</li>
    <li>for MSISDN 41787078880</li>
    <li>refid is given here as an example of parameter that is internal reference ID on Customer's system. It's fully optional and there can be more then one such parameters.</li>
</ul>

<h3>Receiving MNP Query results</h3>

<p>Response begins with IMM. Example:</p>

<code>IMM QID:135c5eea40008a01807c7229938dd852 MCC:228 MNC:03 ERRCODE:000 ERRDESC:</code>

<p>Fields in response:</p>

<div class="table-responsive">
    <table class="table table-hover table-bordered api-table">
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Example</th>
        </tr>
        <tr>
            <td>QID</td>
            <td>Query ID</td>
            <td>135c5eea40008a01807c7229938dd852</td>
        </tr>
        <tr>
            <td>MCC</td>
            <td>MCC</td>
            <td>228</td>
        </tr>
        <tr>
            <td>MNC</td>
            <td>MNC of network where number isported</td>
            <td>03</td>
        </tr>
        <tr>
            <td>ERRCODE</td>
            <td>Error code, see §4</td>
            <td>140</td>
        </tr>
        <tr>
            <td>ERRDESC</td>
            <td>Error Description</td>
            <td>No information about given MSISDN</td>
        </tr>
    </table>
</div>

<p>In case of success,</p>

<div class="table-responsive">
    <table class="table table-hover table-bordered api-table">
        <tr>
            <th>Error code</th>
            <th>Value</th>
            <th>Description</th>
        </tr>
        <tr>
            <td>RC_OK</td>
            <td>000</td>
            <td>OK, no error</td>
        </tr>
        <tr>
            <td>RC_APPLICATION_ERROR</td>
            <td>101</td>
            <td>Internal application error</td>
        </tr>
        <tr>
            <td>RC_NO_ACCOUNT</td>
            <td>103</td>
            <td>No account with givenusername/password</td>
        </tr>
        <tr>
            <td>RC_IP_NOT_ALLOWED</td>
            <td>104</td>
            <td>Sending from client's IP addressnot allowed</td>
        </tr>
        <tr>
            <td>RC_MISSING_MANDATORY_PARAMETER</td>
            <td>110</td>
            <td>Some mandatory parameter ismissing</td>
        </tr>
        <tr>
            <td>RC_UNKNOWN_QUERY_TYPE</td>
            <td>111</td>
            <td>Unknown query type (typeparameter)</td>
        </tr>
        <tr>
            <td>RC_BAD_PARAMETER_VALUE</td>
            <td>112</td>
            <td>Format of some parameter iswrong</td>
        </tr>
        <tr>
            <td>RC_NO_CREDIT</td>
            <td>113</td>
            <td>No credit on account balance</td>
        </tr>
        <tr>
            <td>RC_NOMSISDNINFO</td>
            <td>140</td>
            <td>No information about MSISDN.</td>
        </tr>
        <tr>
            <td>RC_NOMSISDNDEST</td>
            <td>141</td>
            <td>No information about selecteddestination (country) availablefor Customer's account</td>
        </tr>
        <tr>
            <td>RC_UNRELIABLE</td>
            <td>151</td>
            <td>Reliable response couldn't beprovided, but MSISDN ischecked against prefix databaseand MCC/MNC is providedbased on prefix.</td>
        </tr>
    </table>
</div>

<h2>Cookbook</h2>

<h3>How to handle errors</h3>

<p>If HTTP status is 420 (METHOD_INVOCATION_FAILURE) check error code returned in HTTP response in form:</p>

<code>ERR 113 No credit on account balance</code>

<p>When result is received on result-url check first error field (%e) and if it's not 000 ignore mcc (%c) and mnc (%n) information.</p>