<style>   
    dd{
       margin:0px;
       margin-bottom: 15px
}
</style>
<form method="post" class="hcms_form" title="<?php if(isset($this->data['id']) && $this->data['id'] != '') {
     printf($this->translate('Edit \'%s\' Redirection'), $this->escape($this->data['name']));
}else {
    echo $this->translate('Add New Redirection');
      }?>" action="<?php echo $this->url(array('controller' => 'admin-redirect', 'action' => 'edit')) ?>" enctype="application/x-www-form-urlencoded">

    <input type="hidden" id="data[id]" value="<?php echo (isset($this->data['id']))?$this->escape($this->data['id']):'';?>" name="data[id]"/>
    <input type="hidden" name="data[dialog_url]" id="data[dialog_url]"  value="" />
    <input type="hidden" name="data[lang]" id="data[lang]"  value="<?php echo $this->escape($this->data['lang']);?>" />   
    <div class="btn-block">
        <label for="data[name]" title="<?php echo $this->translate('Route Name') ;?>"><?php echo $this->translate('Name');?>:</label>
        <input type="text" title="<?php echo $this->translate('Route Name') ;?>" name="data[name]" title="<?php echo $this->translate('Route Name') ;?>" id="data[name]" value="<?php echo (isset($this->data['name']))? $this->escape($this->data['name']):'';?>" maxlength="100"/>
        <?php echo $this->errorMessages($this->errors['name']);?>
     </div>
    <div class="btn-block">
        <label for="route[uri]" title="<?php echo $this->translate('URL part after language identificator') ;?>"><?php echo $this->translate('URL');?>:</label>
	<div class="input-block" style="border: 0; padding: 0;">
	    <span><?php echo $this->serverUrl()?>/<?php echo ($this->data['lang']!='' ? $this->data['lang'] . "/" : "")?></span>
	    <input type="text" title="<?php echo $this->translate('URL part after language identificator') ;?>" name="data[uri]" id="data[uri]" value="<?php echo (isset($this->data['uri']))?$this->escape($this->data['uri']):'';?>" maxlength="200" style="width: 300px;"/>
	</div>
    </div>
    <div class="btn-block">
        <label for="data[params]" title="url"><?php echo $this->translate('Redirection to');?>:</label>
        <input type="text" title="<?php echo $this->translate('Additional parameters to be appended to URL in the form of &quot;name/value&quot;') ;?>" name="data[params]" id="data[params]" value="<?php echo (isset($this->data['params']))?$this->escape($this->data['params']):'';?>" maxlength="255"/>
        <?php echo $this->errorMessages($this->errors['params']);?>
    </div>    
    <input type="submit" value="<?php echo $this->translate('Save');?>" name="submit[save]" />
</form>