<script type="text/javascript">
            var fileWebRoot = '<?php echo $this->fileWebRoot; ?>';
            var theme = '<?php echo $this->theme; ?>';
</script>
<div id="front-admin-header">
    <ul>
        <li><a href="/en/admin" target="_blank" id="fron-admin-logo"></a></li>
        <li id="front-admin-btn-save" class="fa fa-floppy-o"><span><?php echo $this->translate('Save');?></span></li>
        <li id="front-admin-btn-exit" class="fa fa-times"><span><?php echo $this->translate('Exit Edit Mode');?></span></li>
        <li id="front-admin-btn-logout" class="fa fa-sign-out"><span><?php echo $this->translate('Logout');?></span></li>
    </ul>
</div>