<div class="pageContentHolder eleven columns">    
    <?php $this->headLink()->appendStylesheet( '/modules/fbgallery/css/style.css'); ?>
    <div class="clearfix fbgallery">
    <h3><?php echo $this->translate("Facebook Gallery")?></h3>
    <?php
        if(count($this->paginator) > 0){
            foreach($this->paginator as $album){ ?>
                <div class="album_holder">
                        <a href="<?php echo $this->url(array('module'=>'fbgallery', 'controller' => 'index', 'action' => 'photos', 'url_id' => $album['id'])); ?>">
                            <i style="background-image: url(https://graph.facebook.com/<?php echo $album['id'];?>/picture); background-position: center;"></i>
                        </a>
                </div>
            <?php } ?>
    </div>    
    <div class="clearfix">&nbsp</div>
    <?php
            $this->addScriptPath(APPLICATION_PATH . '/modules/cms/views/scripts/');
            echo $this->paginationControl($this->paginator,'Sliding','paginator.phtml',array('route'=>$this->route,'listingParams'=>$this->listingParams));
        }
        else{
            echo "<div class='videos_content'><p style='text-align:center;'>" . $this->translate('No albums found') . "</p></div>";
        }
    ?>
</div>
<div class="rightSideContent six columns ">
    <div class="socialSideContainer">
        <nav class="socialSide">
            <a href="#" class="facebook"></a>
            <a href="#" class="twitter"></a>
            <a href="#" class="google"></a>
            <a href="#" class="soc1"></a>
            <a href="#" class="linkedIn"></a>
            <a href="#" class="soc2"></a>
            <a href="#" class="soc3"></a>
        </nav> 
    </div>
</div>