<?php
    $this->headScript()->appendFile('/plugins/hfb/js/jquery.hfbSelect.js');
    $this->headScript()->appendFile('/plugins/hfb/js/jquery.hfbSearch.js');
    $this->headScript()->appendFile('/plugins/hfb/js/jquery.hfbList.js');
    $this->headScript()->appendFile('/js/ajaxDialogForm.js');
    $this->headScript()->appendFile('/modules/auth/js/list.js');
?>
<script type="text/javascript">
    function getEditUrl(id){
        return sprintf('/%s/translation/admin-type/edit/id/%d',CURR_LANG,id);
    }

    function editDialog(id){
        ajaxDialogForm.dialog(getEditUrl(id),{
            onClose: function(success){
                if(success){
                    updateList();
                }
            },
            width: 'auto',
            height: 'auto'
        });
    }

    initList('/' + CURR_LANG + '/translation/admin-type/list/',{},function(me,data){
        $("#listContainer").find("a.edit").click(function(){
            editDialog($(this).data('id'));
            return false;
        });
        $("#listContainer").find("a.delete").click(function(){
            alert('delete'+$(this).data('id'));
            return false;
        });
    });
    //init select filter
    $(document).ready(function(){
        $("#langFilter").change(function(){
            updateList('langFilter',$(this).val());
        });
        $("#filter").click(function(){
            var params = $("#listContainer").data('params');
            params['name'] = $('#name').val();
           $("#listContainer").hfbList({
                'params': params
            });
            return false;
        })
        $(".add").click(function(){
            editDialog(null);
            return false;
        });
    });
</script>
<div class="hcms_content_top">
    <h1><?php echo $this->translate('Type'); ?>     </h1>

</div>
<div class="hcms_content">
    <div class="articles"> 
	<div class="hcms_btn_actions translate">
	    <div class="btn-block"> 
		<a href="#" class="add btn btn-small btn-primary"><i class="icon-plus-med"></i><?php echo $this->translate('Add new'); ?></a>
		<div class="hcms_search">
		    <div class="input-group">
			<input name="searchFilter" id="searchFilter" type="text" value="" />
			<div class="input-group-btn"><a href="#" id="searchExecute" class="btn btn-small btn-primary"><?php echo $this->translate("Search"); ?></a></div>
		    </div>
		</div>
	    </div>
	    <div class="btn-block">
		<div class="hcms_block">
		    <div class="input-group">
			<input type="text" class="_input" name="name" id="name" value="" maxlength="100" placeholder="<?php echo $this->translate('Name');?>"/>
			 <div class="input-group-btn"><a href="#" class="btn btn-small btn-primary" id="filter">Filter</a></div>
		    </div>
		</div>
	    </div>
	</div>
	<table class="hcms_table adminList" width="100%">
	    <thead>
		<tr>
		    <th><a href="#" class="sort" data-column="name"><?php echo $this->translate('Name');?><b></b></a></th>
		</tr>
	    </thead>
	    <tbody id="listContainer">
	    </tbody>
	</table>
	<div id="pager" class="pager"></div>
    </div>
</div>
<script type="text/html" id="records_tpl">
<% if (rows.length > 0){
    var rowClass = 'odd';
    %>
    <% for ( var i = 0; i < rows.length; i++ ){
        rowClass = (i % 2 == 0)? 'even':'odd';
    %>
        <tr class="<%=rowClass%>">
            <td class="fixed-width">
                 <%=rows[i].name%>
                <ul class="hcms_menu_actions">
                    <li><a href="#" class="edit" data-id="<%=rows[i].id%>"><span><?php echo $this->translate('Edit');?></span></a></li>
                    <li><a href="#" class="delete" data-id="<%=rows[i].id%>"><span><?php echo $this->translate('Delete');?></span></a></li>
                </ul>
            </td>
        </tr>
    <% } %>
<% } %>
</script>