<?php
$this->doctype('HTML5');
echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="<?php echo $this->currLang; ?>">
<head>
    <base href="<?php echo $this->serverUrl() . $this->fileWebRoot; ?>" />
    <meta charset="utf-8" />
    <?php
        $favicon =  $this->themePath('/images/favicon.ico');
        $this   ->headLink(array('rel' => 'icon', 'href' => $favicon, 'type' => 'image/x-icon'),'PREPEND')
                ->headLink(array('rel' => 'shortcut icon', 'href' => $favicon, 'type' => 'image/x-icon'),'PREPEND'); //fb ico
        //fb sharer
        echo $this->headMeta();
        echo $this->headTitle(); 
        
        ?>
        <!--[if IE 7]>
            <link href="/themes/clockhouse/css/ieStyle.css" media="screen" rel="stylesheet" type="text/css" >
        <![endif]-->
        <!--[if IE 8]>
            <link href="/themes/clockhouse/css/ieStyle.css" media="screen" rel="stylesheet" type="text/css" >
        <![endif]-->
        
        <?php
        $this->headLink()->prependStylesheet($this->themePath('css/style.css'));
        $this->headLink()->prependStylesheet($this->themePath('/css/jquery.bxslider.css'));
        $this->headLink()->prependStylesheet('/plugins/fancybox/jquery.fancybox-1.3.4.css');
        echo $this->headLink();

        $this->headScript()->prependFile('/js/menu.js');
        $this->headScript()->prependFile('/js/php.js');
        $this->headScript()->prependFile('/js/init.js');
        $this->headScript()->prependFile('/js/json2.js');
        
        $this->headScript()->prependFile('/plugins/fancybox/jquery.mousewheel-3.0.4.pack.js');
        $this->headScript()->prependFile('/plugins/fancybox/jquery.fancybox-1.3.4.pack.js');
        $this->headScript()->prependFile('/js/jquery.bxslider.min.js');
        $this->headScript()->prependFile('/js/jquery-1.7.1.min.js');
        echo $this->headScript();
        echo $this->headStyle();
    ?>
<!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

<?php
    //GA
    if(isset ($this->application)){
        $gaSettings = $this->application->get_settings('ga');
        //check ga settings
        if(isset ($gaSettings) && isset ($gaSettings['tracking_id'])){
?>
<script type="text/javascript">
//GA
var _gaq = _gaq || [];
_gaq.push(['_setAccount', '<?php echo $this->escape($gaSettings['tracking_id']);?>']);
_gaq.push(['_trackPageview']);

(function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
})();
</script>
<?php
        }
    }
?>

<?php

   if(isset ($this->page) && null != $this->page->get_code() && '' != $this->page->get_code()){
       $bodyClass = ' class="' . $this->page->get_code() . '"';
   }
   else{
       $bodyClass = '';
   }
?>
</head>

<body <?php echo $bodyClass;?> >
<div class="wrapper">
    <header class="clearfix headerSyle">
        <!--<section class="lang">
            <div id="langswitch" class="langswitch">
                <ul>
                <?php
                if(isset ($this->availableLang) && is_array($this->availableLang) && count($this->availableLang)){foreach ($this->availableLang as $code => $value) {
                    if(isset ($value['front_enabled']) && $value['front_enabled']){
                        $langClass = $this->currLang == $code?"$code active":"$code";
                        echo "<li><a href=\"" . $this->switchLang($code) . "\" class=\"$langClass\">" . $value['name'] . "</a></li>";
                    }
                }}?>
                </ul>
            </div>
        </section>-->
    	<div class="wrap clearfix">
            <a href="<?php echo $this->url(array('module'=> 'default'),'default',true);?>" id="logo">HORISEN CMS</a>
            <nav class="headerNav">
                <?php echo $this->navigation()->menu()->setUseTranslator(false)->renderMenu($this->menuItems['main'],array('ulClass' => 'mainMenu', 'indent' => 20, 'maxDepth' => 1)); ?>
                
             
            </nav>
        </div>
       <!-- <nav class="breadcrumb">
            <?php echo $this->navigation()->breadcrumbs($this->menuItems['main'])->setUseTranslator(false)->setLinkLast(false)->setMinDepth(0)->render(); ?>
        </nav>-->
       <div class="menuLine"></div>
    </header>
    <section class="content">
        <div class="contentWrapper">
            <?php echo $this->layout()->content; ?>
        </div>
    </section>
    
</div>
<footer class="clearfix footerStyle">
    <nav class="footerNav">
        <?php echo $this->navigation()->menu()->setUseTranslator(false)->renderMenu($this->menuItems['footer'],array('ulClass' => 'footerMenu', 'indent' => 20, 'maxDepth' => 1)); ?>
        <a href="http://www.horisen.com" target="_blank" class="footLogo"> </a>
    </nav>
    <div class="footerLine">
        <div>
            &copy; <?php echo date("Y"); ?> HORISEN CMS. All rights reserved
        </div>
    </div>

</footer>


</body>
</html>
