
<script type="text/javascript">
    $(document).ready(function(){
        $("#username").focus();
    });
</script>


<h1><?php echo $this->translate("Members area");?></h1>
<div class="row">
    <form id="login" class="form-horizontal" name="login" method="post" action="">
        <div class="form-group">
            <label class="col-sm-3 control-label"><?php echo $this->translate("Username") . ": "; ?></label>
            <div class="col-sm-9">
                <input class="form-control" type="text" id="username" name="username" value="<?php if(isset($this->username)){echo $this->escape($this->username);}?>" />
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3 control-label"><?php echo $this->translate("Password"). ": "; ?></label>
            <div class="col-sm-9">
                <input class="form-control" type="password" id="passowrd" name="password" value="<?php if(isset($this->password)){echo $this->escape($this->password);}?>" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-lg-12">
                <span><?php echo $this->messages; ?></span>
            </div>
            <div class="col-lg-1 col-lg-offset-10">
                <input class="button" type="submit" name="submit" value="<?php echo $this->translate("Login"); ?>" />
            </div>
        </div>
    </form>
</div>
