<script type="text/javascript">
    $(document).ready(function(){
        
        /* ------Remove Error Fields if they exist from form on key pressed  */
       $("input[type=text], textarea").keypress(function(){
           $(this).removeClass("form_field_error");
       });
       $("select").change(function(){
           $(this).removeClass("form_field_error");
       });

       $("li input[type=radio]").change(function(){
           $("li").removeClass("form_field_error_radio");
           $("#gender").addClass("gender");
       });
    });
</script> 


<div class="pageContentHolder eleven columns">

<?php echo $this->contentBlock('newsletter-intro-text', CURR_LANG);?>
    
<form id="newsletter_form" class="newsletter" method="post" action="<?php echo $this->url(array('module'=>'newsletter','controller'=>'index','action'=>'index'),'cms',true);?>" enctype="application/x-www-form-urlencoded">
    <input type="hidden" name="data[check]" id="data[check]"  value="" />
    <ul>
        <li <?php if(isset ($this->errors['gender'])){echo 'class="form_field_error_radio"';}?>>
            <span><?php echo $this->translate('Gender:');?>*</span>
            <input type="radio" class="contact_form_radio" name="data[gender]" <?php if($this->data['gender']=="Male") echo "checked=\"checked\"";?> value="Male" ><span><?php echo $this->translate('Male')?></span>
            <input type="radio" class="contact_form_radio" name="data[gender]" <?php if($this->data['gender']=="Female") echo "checked=\"checked\"";?> value="Female" ><span><?php echo $this->translate('Female')?></span>

        </li>
        <li>
            <!--<label for="data[first_name]"><?php echo $this->translate('First Name');?>:</label>-->
            <input type="text" <?php if(isset ($this->errors['first_name'])){echo 'class="form_field_error"';}?>  placeholder="<?php echo $this->translate('First Name'); ?>*" name="data[first_name]" id="data[first_name]" value="<?php echo (isset($this->data['first_name']))? $this->escape($this->data['first_name']) :""; ?>" maxlength="20"  />

        </li>
        <li>
            <!--<label for="data[last_name]"><?php echo $this->translate('Last Name');?>:</label>-->
            <input type="text" <?php if(isset ($this->errors['last_name'])){echo 'class="form_field_error"';}?>  placeholder="<?php echo $this->translate('Last Name');?>*" name="data[last_name]" id="data[last_name]"  value="<?php echo (isset($this->data['last_name']))?$this->escape($this->data['last_name']):""; ?>" maxlength="20" />

        </li>
        <li>
            <!--<label for="data[address]"><?php echo $this->translate('Address');?>:</label>-->
            <input type="text" <?php if(isset ($this->errors['address'])){echo 'class="form_field_error"';}?> placeholder="<?php echo $this->translate('Address');?>" name="data[address]" id="data[street]" value="<?php echo (isset($this->data['address']))? $this->escape($this->data['address']):""; ?>" maxlength="30"  />
        </li>
        <li class="zipCity">
            <!--<label for="data[ZIP]"><?php echo $this->translate('ZIP') . "/" . $this->translate('City');?>:</label>-->
            <input placeholder="<?php echo $this->translate('ZIP');?>" class="half zip <?php if(isset ($this->errors['zip'])){echo ' form_field_error';}?>" type="text" name="data[zip]" id="data[zip]" value="<?php echo (isset($this->data['zip']))? $this->escape($this->data['zip']):""; ?>" maxlength="6" />
            <input placeholder="<?php echo $this->translate('City');?>" class="half city <?php if(isset ($this->errors['city'])){echo ' form_field_error';}?>"  type="text" name="data[city]" id="data[city]" value="<?php echo (isset($this->data['city']))? $this->escape($this->data['city']):""; ?>" maxlength="30" />
        </li>
       
        <li>
           <select name="data[country]" id="data[country]" class="name">
                <option value=""><?php echo "-- " . $this->translate('Country:') . " --"?></option>
                <?php foreach ($this->countries as $country) { ?>
                <option value="<?php echo $country->get_name(); ?>" <?php if($this->data['country']==$country->get_name()) echo "selected=\"selected\""; ?>><?php echo $country->get_name(); ?></option>
                <?php } ?>
            </select>
        </li>
        <li>
            <input <?php if(isset ($this->errors['telephone'])){echo 'class="form_field_error"';}?> placeholder="<?php echo $this->translate('Telephone');?>"  type="text" name="data[telephone]" id="data[telephone]" value="<?php echo (isset($this->data['telephone']))? $this->escape($this->data['telephone']):""; ?>" maxlength="15" />
        </li>
        <li>
            <!--<label for="data[email]"><?php echo $this->translate('E-Mail');?>:</label>-->
            <input type="text" <?php if(isset ($this->errors['email'])){echo 'class="form_field_error"';}?>  placeholder="<?php echo $this->translate('E-Mail');?>*" name="data[email]" id="data[email]" value="<?php echo (isset($this->data['email']))? $this->escape($this->data['email']):""; ?>" maxlength="60"  />

        </li>

    </ul>
        <ul class="buttons cfix">
            <li style="width:100%;">
                
                <input class="button" id="resetButton" type="submit" value="<?php echo $this->translate("Unsubscribe"); ?>" name="submit[unsubscribe]" />
                <input class="button newsButton" id="sendButton" type="submit" value="<?php echo $this->translate("Subscribe"); ?>" name="submit[save]" />
            </li>
        </ul>
    </form>
</div>
<div class="rightSideContent six columns ">
    <div class="socialSideContainer">
        <nav class="socialSide">
            <a href="#" class="facebook"></a>
            <a href="#" class="twitter"></a>
            <a href="#" class="google"></a>
            <a href="#" class="soc1"></a>
            <a href="#" class="linkedIn"></a>
            <a href="#" class="soc2"></a>
            <a href="#" class="soc3"></a>
        </nav> 
    </div>
</div>