<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Daily Report</title>
    </head>
    <body>
        <h1>Subscriptions report <?php echo $this->date;?></h1>

        <p>Subscriptions:  <?php echo count($this->subscriptions);?></p>
        <p>Un-subscriptions:  <?php echo count($this->unsubscriptions);?></p>
    </body>
</html>
