<?php
if(isset($this->items) && count($this->items)){
    $sliderSpeed = ($this->teaser->get_content('speed'))? $this->teaser->get_content('speed'): 4000;
    $boxImages = isset($this->box['params']['images'])? $this->box['params']['images']: array();
    $stylesQuery = array();
    $stylesGlobal = array();
?>
    <div id="sequence" data-speed="<?php echo $sliderSpeed; ?>">
        <div class="intro-load">
            <svg class="preloading" xmlns="http://www.w3.org/2000/svg">
                <circle class="circle" cx="6" cy="6" r="6"></circle>
                <circle class="circle" cx="22" cy="6" r="6"></circle>
                <circle class="circle" cx="38" cy="6" r="6"></circle>
            </svg>
        </div>
        <div class="sequence-next-container">
            <img class="sequence-next" src="/themes/genesis/images/arrows-01.png" alt="Next" />
        </div>
        <ul class="sequence-canvas">
<?php
    $orderNum = 0;
    /* @var $item Teaser_Model_Item */
    foreach ($this->items as $item) {
        $orderNum++;
        $liClass = ($orderNum == 1)? ' class="animate-in"' : '';
        foreach ($boxImages  as $imageKey => $imageDef) {
            $image = array(
                'path'  => $item->get_content($imageKey),
                'index' => $orderNum
            );
            if($imageDef['media_query']){
                $stylesQuery[$imageDef['media_query']][] = $image;
            }else{
                $stylesGlobal[] = $image;
            }
        }
        $liId = ($item->get_content('css_id'))? ' id="' . $item->get_content('css_id') . '"' : '';
?>
            <li<?php echo $liId . $liClass;?>>
                <div class="info">
                    <h1><?php echo $item->get_title();?></h1>
                    <h2><?php echo $item->get_content('subtitle');?></h2>
                    <a class="hwButton" href="<?php echo $item->get_content('link');?>" target="<?php echo $item->get_content('link_target')? $item->get_content('link_target'): '_self';?>"><?php echo ($item->get_content('button_text'))? $item->get_content('button_text'): $this->translate('Learn more'); ?></a>
                </div>
                <div class="back slide<?php echo $orderNum; ?>"></div>
            </li>
<?php
    } //end for each
    $style = '';
    //append global styles
    foreach ($stylesGlobal as $image) {
        $style .= "\n.slide" . $image['index'] . ' {background-image: url("' . $image['path'] . '");}';
    }
    //append mquery styles
    foreach ($stylesQuery as $query => $images) {
        $style .= "\n@media screen and " . $query . " {";
        foreach ($images as $image) {
            $style .= "\n    .slide" . $image['index'] . ' {background-image: url("' . $image['path'] . '");}';
        }
        $style .= "\n}";
    }
    //append custom css
    /* @var $item Teaser_Model_Item */
    foreach ($this->items as $item) {
        if(null != $item->get_content('css_text')){
            $style .= "\n" . $item->get_content('css_text');
        }
    }
    $this->headStyle()->appendStyle($style);
?>
        </ul>
    </div>
<?php
}//end global if
?>