<?php 

$settings = $this->application->get_twitter_settings(); 

$twitter_url = "https://api.twitter.com/1/statuses/user_timeline.json?include_entities=true&include_rts=true&screen_name=".$settings['screen_name']."&count=2";
$results = file_get_contents($twitter_url);

$json_tweets=json_decode($results,true);
foreach($json_tweets as $tweet){
?>

<div>
    <?php echo $tweet['text']; ?>
</div>

<?php
}
?>

